'use strict';

const data = {

"cursa-bombers-barcelona": {
  "slugEs": "cursa-bombers-barcelona",
  "slugEn": "cursa-bombers-barcelona",
  "hasEn": false,
  "nameEs": "Cursa dels Bombers Barcelona",
  "nameEn": "",
  "city": "Barcelona",
  "region": "Cataluña",
  "country": "ES",
  "distance": "10K",
  "distanceLabel": "10K",
  "distanceLabelEn": "10K",
  "distanceCategory": "10k",
  "dateMonth": 4,
  "dateText2026Es": "19 de abril de 2026",
  "dateText2026En": "",
  "startDate": "2026-04-19",
  "priceRange": "18-25",
  "currency": "EUR",
  "maxParticipants": 15000,
  "elevationEs": "Llano urbano",
  "elevationEn": "",
  "heroImage": "https://images.pexels.com/photos/3621175/pexels-photo-3621175.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/3621180/pexels-photo-3621180.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "Cursa dels Bombers Barcelona 2026: inscripción, recorrido, consejos y toda la información sobre la carrera de 10K más emblemática de Barcelona con 15.000 participantes.",
  "metaDescriptionEn": "",
  "descriptionEs": "La Cursa dels Bombers de Barcelona es una de las carreras populares más antiguas y queridas de la ciudad condal. Organizada por el cuerpo de Bomberos de Barcelona, esta prueba de 10 kilómetros se celebra cada mes de abril y reúne a miles de corredores que recorren las calles más icónicas de la capital catalana en un ambiente festivo y solidario. Parte de la recaudación se destina a proyectos sociales y de prevención vinculados al cuerpo de bomberos, lo que añade un componente solidario que la hace aún más especial.\n\nDesde sus primeras ediciones, la Cursa dels Bombers ha crecido de forma exponencial hasta consolidarse como una de las citas imprescindibles del calendario atlético barcelonés. Cada año, alrededor de 15.000 corredores de todos los niveles se dan cita en la línea de salida, desde atletas populares que buscan mejorar su marca personal hasta familias y grupos de amigos que simplemente quieren disfrutar de una mañana de deporte al aire libre en un entorno incomparable.\n\nEl ambiente previo a la carrera es una auténtica fiesta. La zona de salida se convierte en un espectáculo con exhibiciones del cuerpo de bomberos, música en directo y actividades para los más pequeños. Los bomberos participan en la carrera equipados con parte de su indumentaria profesional, añadiendo un toque de espectacularidad que entusiasma al público que se agolpa en las aceras para animar a los participantes.\n\nEl recorrido ofrece una oportunidad única de correr por el corazón de Barcelona, pasando por algunos de sus monumentos y espacios más emblemáticos. El trazado es predominantemente llano con alguna suave ondulación, lo que lo convierte en un circuito apto para todos los niveles y especialmente atractivo para quienes buscan debutar en la distancia de los 10 kilómetros. Los avituallamientos están bien distribuidos y la organización despliega un dispositivo sanitario completo a lo largo de todo el recorrido.\n\nLa inscripción incluye camiseta técnica conmemorativa, dorsal con chip de cronometraje, bolsa del corredor y seguro de responsabilidad civil. Se recomienda formalizar la inscripción con varias semanas de antelación ya que las plazas se agotan rápidamente dada la popularidad del evento. La feria del corredor abre sus puertas dos días antes de la prueba en un recinto céntrico de fácil acceso.",
  "descriptionEn": "",
  "routeEs": "El recorrido de la Cursa dels Bombers arranca en la Avenida Maria Cristina, junto a la Font Màgica de Montjuïc, y desciende por la Gran Via de les Corts Catalanes en dirección al centro de la ciudad. Los corredores atraviesan la Plaza de España y continúan por el Paral·lel hasta alcanzar el Passeig de Colom junto al Puerto Olímpico. El trazado gira hacia la Barceloneta y recorre el frente marítimo antes de regresar por la Via Laietana hacia la zona de meta. El asfalto está en buen estado y las calles son amplias, lo que garantiza fluidez incluso en los primeros kilómetros donde la densidad de corredores es mayor. Hay puntos de avituallamiento en los kilómetros 3, 5 y 8 con agua y bebida isotónica.",
  "routeEn": "",
  "tipsEs": [
    "Llega con al menos una hora de antelación para disfrutar de las exhibiciones de los bomberos antes de la salida",
    "Utiliza transporte público ya que la zona de salida en Montjuïc tiene acceso directo por metro (L1 y L3, parada Espanya)",
    "Lleva ropa ligera ya que abril en Barcelona suele ofrecer temperaturas agradables de entre 15 y 20 grados",
    "Si es tu primera 10K aprovecha el trazado llano para mantener un ritmo constante sin arriesgar en los primeros kilómetros",
    "Queda con tu grupo en la fuente de Montjuïc como punto de encuentro ya que es visible desde toda la zona de salida"
  ],
  "tipsEn": [],
  "faqEs": [
    {"q": "¿Cuándo se celebra la Cursa dels Bombers Barcelona 2026?", "a": "La Cursa dels Bombers de Barcelona 2026 está prevista para el 19 de abril. La salida se realiza habitualmente a las 9:00 de la mañana desde la Avenida Maria Cristina."},
    {"q": "¿Cuánto cuesta la inscripción en la Cursa dels Bombers?", "a": "El precio de la inscripción oscila entre 18 y 25 euros dependiendo del periodo de registro. La inscripción anticipada tiene un precio reducido y se recomienda no esperar al último momento ya que las plazas son limitadas a 15.000 participantes."},
    {"q": "¿Es apta la Cursa dels Bombers para principiantes?", "a": "Sí, es una carrera ideal para debutar en los 10 kilómetros. El recorrido es llano, el ambiente es festivo y la organización permite un tiempo máximo generoso. Muchos participantes la eligen como su primera carrera popular."},
    {"q": "¿Qué incluye la inscripción de la Cursa dels Bombers?", "a": "La inscripción incluye camiseta técnica conmemorativa, dorsal con chip de cronometraje electrónico, bolsa del corredor con productos de los patrocinadores, seguro de responsabilidad civil y acceso a los avituallamientos del recorrido."},
    {"q": "¿Dónde se recoge el dorsal de la Cursa dels Bombers?", "a": "El dorsal se recoge en la feria del corredor que se instala en la zona de Montjuïc dos días antes de la carrera. Es imprescindible presentar el DNI o documento acreditativo y el justificante de inscripción. No se entregan dorsales el día de la carrera."}
  ],
  "faqEn": [],
  "relatedPlans": ["10k-principiantes", "10k-sub-50", "10k-sub-45"],
  "relatedEvents": "barcelona"
},

"carrera-san-anton-madrid": {
  "slugEs": "carrera-san-anton-madrid",
  "slugEn": "carrera-san-anton-madrid",
  "hasEn": false,
  "nameEs": "Carrera de San Antón Madrid",
  "nameEn": "",
  "city": "Madrid",
  "region": "Comunidad de Madrid",
  "country": "ES",
  "distance": "10K",
  "distanceLabel": "10K",
  "distanceLabelEn": "10K",
  "distanceCategory": "10k",
  "dateMonth": 1,
  "dateText2026Es": "17 de enero de 2026",
  "dateText2026En": "",
  "startDate": "2026-01-17",
  "priceRange": "15-22",
  "currency": "EUR",
  "maxParticipants": 10000,
  "elevationEs": "Llano urbano",
  "elevationEn": "",
  "heroImage": "https://images.pexels.com/photos/2404050/pexels-photo-2404050.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/2404055/pexels-photo-2404055.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "Carrera de San Antón Madrid 2026: inscripción, recorrido nocturno, consejos y todo lo que necesitas para correr la 10K más antigua de Madrid con 10.000 participantes.",
  "metaDescriptionEn": "",
  "descriptionEs": "La Carrera de San Antón es la prueba atlética popular más antigua de Madrid y una de las más veteranas de toda España. Se celebra cada mes de enero coincidiendo con las fiestas de San Antonio Abad, patrón de los animales, y su carácter nocturno la convierte en una experiencia única dentro del calendario de carreras populares madrileñas. Correr por el centro de Madrid cuando las luces de la ciudad iluminan el recorrido es una sensación que todo runner debería vivir al menos una vez.\n\nLa historia de esta carrera se remonta a décadas atrás, cuando un grupo reducido de atletas populares decidió celebrar la festividad de San Antón con una prueba por las calles del barrio de Chueca. Lo que empezó como una carrera de barrio se ha transformado con los años en un evento multitudinario que congrega a más de 10.000 corredores y que marca el pistoletazo de salida del calendario atlético madrileño cada temporada.\n\nEl carácter invernal de la prueba le otorga un encanto especial. Las temperaturas frescas de enero en Madrid, normalmente entre 3 y 10 grados, son ideales para correr a buen ritmo. La nocturnidad de la carrera, con salida al atardecer, crea una atmósfera mágica cuando miles de corredores iluminados por las farolas avanzan por las calles del centro mientras los madrileños les animan desde las aceras y los balcones.\n\nLa organización ha sabido mantener el espíritu tradicional de la carrera al tiempo que moderniza sus servicios: cronometraje con chip, avituallamientos bien equipados, zona de calentamiento dirigido y una feria del corredor cada vez más completa. El recorrido está homologado por la Real Federación Española de Atletismo, lo que permite validar las marcas personales obtenidas en la prueba.\n\nLa inscripción incluye camiseta técnica oficial, dorsal con chip, bolsa del corredor y seguro médico. Dada la fecha de celebración en pleno invierno, es recomendable llevar ropa de abrigo para antes y después de la carrera, ya que la espera en la zona de salida puede ser fría. La prueba cuenta además con una categoría de marcha nórdica que permite la participación de personas que prefieren caminar el recorrido a buen ritmo.",
  "descriptionEn": "",
  "routeEs": "El recorrido de la Carrera de San Antón discurre íntegramente por el centro de Madrid, con salida y meta en la calle Hortaleza, junto a la iglesia de San Antón en el barrio de Chueca. El circuito desciende por la Gran Vía hasta la Plaza de España, gira hacia la Plaza de Oriente frente al Palacio Real y regresa por la calle Mayor y la Puerta del Sol hasta completar el bucle por las calles del centro histórico. El trazado es prácticamente llano con alguna suave rampa en la zona de Gran Vía. Las calles son amplias y el asfalto está en buen estado. Los avituallamientos se sitúan en los kilómetros 3 y 7 con agua y bebida isotónica. La iluminación urbana garantiza buena visibilidad en todo el recorrido nocturno.",
  "routeEn": "",
  "tipsEs": [
    "Lleva varias capas de ropa de abrigo para la espera previa ya que las temperaturas nocturnas de enero en Madrid pueden bajar de los 5 grados",
    "Usa elementos reflectantes o ropa con detalles fluorescentes para ser más visible durante el recorrido nocturno",
    "Calienta bien antes de la salida ya que el frío puede provocar tirones musculares si no preparas el cuerpo adecuadamente",
    "Aprovecha el primer kilómetro cuesta abajo por Gran Vía para encontrar tu ritmo sin forzar el arranque",
    "Recoge tu dorsal en la feria del corredor el día anterior para evitar aglomeraciones y llegar relajado a la salida"
  ],
  "tipsEn": [],
  "faqEs": [
    {"q": "¿Cuándo se celebra la Carrera de San Antón Madrid 2026?", "a": "La Carrera de San Antón 2026 se celebra el sábado 17 de enero. La salida está prevista al atardecer, habitualmente entre las 17:30 y las 18:00 horas, lo que la convierte en una carrera nocturna."},
    {"q": "¿Es una carrera nocturna la San Antón de Madrid?", "a": "Sí, la Carrera de San Antón es una de las pocas carreras nocturnas del calendario madrileño. La salida se produce al caer la tarde y gran parte del recorrido transcurre ya de noche, con la iluminación urbana del centro de Madrid como escenario."},
    {"q": "¿Cuánto cuesta inscribirse en la Carrera de San Antón?", "a": "El precio de inscripción varía entre 15 y 22 euros según el periodo de registro. La tarifa más económica corresponde al periodo de inscripción anticipada que suele abrirse en noviembre. Las plazas están limitadas a 10.000 participantes."},
    {"q": "¿Qué distancia tiene la Carrera de San Antón?", "a": "La distancia oficial es de 10 kilómetros con recorrido homologado por la Real Federación Española de Atletismo. También existe una modalidad de marcha nórdica sobre el mismo recorrido para quienes prefieran caminar."},
    {"q": "¿Dónde está la salida y meta de la Carrera de San Antón?", "a": "La salida y la meta se ubican en la calle Hortaleza, en el barrio de Chueca, junto a la iglesia de San Antón. La estación de metro más cercana es Chueca (línea 5) o Gran Vía (líneas 1 y 5)."}
  ],
  "faqEn": [],
  "relatedPlans": ["10k-principiantes", "10k-sub-50", "10k-sub-45"],
  "relatedEvents": "madrid"
},

"10k-valencia": {
  "slugEs": "10k-valencia",
  "slugEn": "10k-valencia",
  "hasEn": false,
  "nameEs": "10K Valencia Trinidad Alfonso",
  "nameEn": "",
  "city": "Valencia",
  "region": "Comunidad Valenciana",
  "country": "ES",
  "distance": "10K",
  "distanceLabel": "10K",
  "distanceLabelEn": "10K",
  "distanceCategory": "10k",
  "dateMonth": 1,
  "dateText2026Es": "11 de enero de 2026",
  "dateText2026En": "",
  "startDate": "2026-01-11",
  "priceRange": "20-28",
  "currency": "EUR",
  "maxParticipants": 12000,
  "elevationEs": "Llano urbano",
  "elevationEn": "",
  "heroImage": "https://images.pexels.com/photos/1571944/pexels-photo-1571944.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/1571948/pexels-photo-1571948.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "10K Valencia Trinidad Alfonso 2026: inscripción, recorrido rápido, consejos y toda la info sobre la 10K más veloz de España con récords mundiales y 12.000 corredores.",
  "metaDescriptionEn": "",
  "descriptionEs": "La 10K Valencia Trinidad Alfonso es considerada la carrera de 10 kilómetros más rápida de España y una de las más veloces del mundo. Celebrada cada mes de enero en la ciudad del running por excelencia, esta prueba forma parte del ecosistema de carreras de la Fundación Trinidad Alfonso que incluye también el Maratón Valencia y el Medio Maratón Valencia, consolidando a la capital del Turia como referencia internacional del atletismo popular.\n\nEl circuito de la 10K Valencia ha sido diseñado específicamente para batir récords. Su trazado completamente llano, la ausencia de curvas cerradas y la cercanía al mar que garantiza temperaturas suaves incluso en enero hacen de esta prueba el escenario perfecto para buscar marcas personales. No es casualidad que varios récords nacionales e internacionales de la distancia se hayan conseguido en las calles de Valencia, atrayendo cada año a una élite internacional de primer nivel.\n\nPero la 10K Valencia no es solo para atletas de élite. De los 12.000 participantes que llenan las calles, la inmensa mayoría son corredores populares que buscan disfrutar de un recorrido rápido en una ciudad que vive y respira running. La organización, a cargo de la SD Correcaminos bajo el paraguas de la Fundación Trinidad Alfonso, es impecable: cronometraje de alta precisión, avituallamientos estratégicamente ubicados, dispositivo médico completo y una logística que permite gestionar el volumen de corredores con eficiencia.\n\nLa experiencia comienza días antes en la Feria del Corredor, instalada en la Ciudad de las Artes y las Ciencias, donde se recogen los dorsales y se puede disfrutar de exposiciones, charlas técnicas y stands de marcas deportivas. El ambiente en Valencia durante el fin de semana de carrera es excepcional, con la ciudad volcada en apoyar a los corredores desde cada esquina del recorrido.\n\nLa inscripción incluye camiseta técnica oficial de alta calidad, dorsal con chip de cronometraje, bolsa del corredor premium, medalla de finisher y seguro deportivo. Valencia se ha ganado a pulso su reputación como la ciudad del running en España y la 10K Trinidad Alfonso es la puerta de entrada perfecta a su ecosistema de carreras.",
  "descriptionEn": "",
  "routeEs": "El recorrido de la 10K Valencia está homologado por World Athletics y diseñado para la velocidad. La salida se produce en la Alameda, junto al antiguo cauce del río Turia, y el circuito discurre por avenidas amplias y rectas del centro de la ciudad como la Avenida del Puerto, la calle Colón y la Gran Vía Marqués del Turia. El trazado es completamente llano, sin un solo metro de desnivel significativo, y las curvas son amplias y progresivas. La meta se sitúa junto a la Ciudad de las Artes y las Ciencias en un tramo final recto y espectacular. Los avituallamientos se distribuyen en los kilómetros 3, 5 y 8 con agua, bebida isotónica y esponjas húmedas.",
  "routeEn": "",
  "tipsEs": [
    "Aprovecha el circuito llano y rápido para intentar tu mejor marca personal en 10K con una estrategia de ritmo constante",
    "Recoge tu dorsal en la feria de la Ciudad de las Artes y las Ciencias con antelación y disfruta del ambiente previo",
    "Aunque es enero las temperaturas en Valencia suelen ser suaves así que viste con ropa ligera de competición",
    "Colócate en el cajón de salida adecuado a tu ritmo objetivo para evitar perder segundos esquivando corredores más lentos",
    "Hidrátate bien los días previos ya que la brisa marina puede generar una falsa sensación de frescor que lleve a descuidar la hidratación"
  ],
  "tipsEn": [],
  "faqEs": [
    {"q": "¿Cuándo se celebra la 10K Valencia Trinidad Alfonso 2026?", "a": "La 10K Valencia Trinidad Alfonso 2026 se celebra el domingo 11 de enero. La salida está prevista a las 9:00 de la mañana para aprovechar las condiciones óptimas de temperatura de primera hora."},
    {"q": "¿Es la 10K Valencia una carrera rápida?", "a": "Sí, es considerada la 10K más rápida de España y una de las más veloces del mundo. Su circuito completamente llano, sin curvas cerradas y con clima templado en enero, la convierte en el escenario ideal para batir marcas personales y récords."},
    {"q": "¿Cuánto cuesta la inscripción en la 10K Valencia?", "a": "El precio de inscripción varía entre 20 y 28 euros según el periodo de registro. La tarifa más económica corresponde al periodo early bird que suele abrirse meses antes del evento. Las plazas están limitadas a 12.000 participantes."},
    {"q": "¿Dónde se recoge el dorsal de la 10K Valencia?", "a": "El dorsal se recoge en la Feria del Corredor ubicada en la Ciudad de las Artes y las Ciencias. La feria abre jueves y viernes antes de la carrera y es obligatorio presentar el DNI. No se entregan dorsales el domingo de carrera."},
    {"q": "¿Es apta la 10K Valencia para corredores principiantes?", "a": "Sí, aunque su reputación como carrera rápida pueda intimidar, la 10K Valencia acoge corredores de todos los niveles. El circuito llano y la excelente organización la hacen perfecta tanto para debutar en la distancia como para buscar un nuevo récord personal."}
  ],
  "faqEn": [],
  "relatedPlans": ["10k-principiantes", "10k-sub-50", "10k-sub-45"],
  "relatedEvents": "valencia"
},

"volta-a-peu-valencia": {
  "slugEs": "volta-a-peu-valencia",
  "slugEn": "volta-a-peu-valencia",
  "hasEn": false,
  "nameEs": "Volta a Peu València",
  "nameEn": "",
  "city": "Valencia",
  "region": "Comunidad Valenciana",
  "country": "ES",
  "distance": "10K",
  "distanceLabel": "10K",
  "distanceLabelEn": "10K",
  "distanceCategory": "10k",
  "dateMonth": 12,
  "dateText2026Es": "31 de diciembre de 2026",
  "dateText2026En": "",
  "startDate": "2026-12-31",
  "priceRange": "10-18",
  "currency": "EUR",
  "maxParticipants": 15000,
  "elevationEs": "Llano urbano",
  "elevationEn": "",
  "heroImage": "https://images.pexels.com/photos/2538107/pexels-photo-2538107.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/2538110/pexels-photo-2538110.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "Volta a Peu València 2026: la carrera de San Silvestre de Valencia. Inscripción, recorrido, consejos y todo sobre la 10K de fin de año con 15.000 participantes.",
  "metaDescriptionEn": "",
  "descriptionEs": "La Volta a Peu de València es la tradicional carrera de San Silvestre de la capital del Turia, una prueba que despide el año corriendo por las calles de una de las ciudades más amables para el running de toda España. Cada 31 de diciembre, más de 15.000 corredores se congregan en el centro de Valencia para celebrar la última carrera del año en un ambiente festivo, familiar y lleno de alegría que combina deporte y fiesta de Nochevieja.\n\nLa Volta a Peu es mucho más que una simple carrera: es una tradición valenciana que forma parte del ADN deportivo de la ciudad. Familias enteras, grupos de amigos, clubes de atletismo y corredores solitarios se unen en una celebración colectiva donde el cronómetro pasa a segundo plano y lo que importa es compartir los últimos kilómetros del año con miles de personas que sienten la misma pasión por correr. Muchos participantes acuden disfrazados, creando una atmósfera carnavalesca que llena de color y risas cada tramo del recorrido.\n\nA pesar de su carácter festivo, la Volta a Peu también cuenta con una competición seria en cabeza de carrera. Los mejores atletas valencianos y nacionales se disputan la victoria en un circuito rápido y llano que permite marcas muy competitivas. La organización garantiza un cronometraje preciso con chip para todos los participantes, lo que permite a cada corredor conocer su tiempo oficial independientemente de su posición en la clasificación.\n\nEl clima de Valencia en diciembre es uno de los grandes atractivos de esta San Silvestre. Mientras en otras ciudades españolas las temperaturas pueden ser gélidas, en Valencia es habitual correr con 10 a 15 grados y cielos despejados, condiciones ideales para disfrutar de una carrera cómoda sin pasar frío. Esta ventaja climática explica en parte el éxito de participación que año tras año supera las previsiones de la organización.\n\nLa inscripción es una de las más accesibles del calendario valenciano, con precios populares que incluyen camiseta conmemorativa, dorsal con chip, seguro y avituallamientos. Al terminar la carrera, muchos participantes aprovechan para disfrutar de una comida de Nochevieja en los numerosos restaurantes del centro de Valencia, convirtiendo la jornada en una experiencia completa de deporte y gastronomía.",
  "descriptionEn": "",
  "routeEs": "El recorrido de la Volta a Peu València transcurre por las calles más céntricas y emblemáticas de la ciudad. La salida se produce en la Plaza del Ayuntamiento y el circuito recorre la calle de la Paz, cruza junto la Catedral y el Miguelete, desciende por la calle San Vicente Mártir y bordea el Jardín del Turia antes de regresar al punto de partida por las Grandes Vías. El trazado es completamente llano y transcurre íntegramente por asfalto en buen estado. Las calles son amplias lo que permite absorber bien el gran volumen de participantes. Los avituallamientos se ubican en los kilómetros 3 y 7 con agua y fruta. La meta en la Plaza del Ayuntamiento ofrece un marco espectacular para cerrar el año.",
  "routeEn": "",
  "tipsEs": [
    "Si quieres competir colócate en las primeras filas pero si vas a disfrutar del ambiente festivo no te preocupes por tu posición de salida",
    "Lleva ropa cómoda y si te animas un disfraz divertido ya que es tradición en las carreras de San Silvestre",
    "Desayuna ligero unas dos horas antes de la carrera ya que la salida suele ser a media mañana",
    "Reserva restaurante para la comida de Nochevieja con antelación si planeas quedarte a celebrar en el centro de Valencia",
    "Usa transporte público para llegar a la Plaza del Ayuntamiento ya que el centro estará cortado al tráfico desde primera hora"
  ],
  "tipsEn": [],
  "faqEs": [
    {"q": "¿Cuándo se celebra la Volta a Peu València 2026?", "a": "La Volta a Peu València 2026 se celebra el 31 de diciembre, como es tradición cada año. La salida está prevista a media mañana, habitualmente entre las 10:00 y las 11:00 horas, permitiendo a los participantes disfrutar del resto del día de Nochevieja."},
    {"q": "¿Es obligatorio ir disfrazado en la Volta a Peu?", "a": "No es obligatorio en absoluto, pero es una tradición muy arraigada en las carreras de San Silvestre. Muchos participantes acuden con disfraces divertidos y creativos, lo que añade un componente festivo único. Puedes correr con ropa deportiva normal sin ningún problema."},
    {"q": "¿Cuánto cuesta la inscripción en la Volta a Peu València?", "a": "El precio de inscripción oscila entre 10 y 18 euros, siendo una de las carreras más asequibles del calendario valenciano. La inscripción incluye camiseta conmemorativa, dorsal con chip de cronometraje y seguro deportivo."},
    {"q": "¿La Volta a Peu es apta para familias y niños?", "a": "Sí, la Volta a Peu es una carrera muy familiar. Además de la prueba principal de 10K existe habitualmente una carrera infantil de menor distancia. El ambiente festivo y la ausencia de dificultad técnica la hacen perfecta para participar en familia."},
    {"q": "¿Se puede conseguir buena marca en la Volta a Peu València?", "a": "Sí, a pesar de su carácter festivo el recorrido es llano y rápido con cronometraje oficial con chip. Los corredores que buscan competir pueden situarse en los primeros cajones de salida para evitar aglomeraciones y buscar su mejor marca para cerrar el año."}
  ],
  "faqEn": [],
  "relatedPlans": ["10k-principiantes", "10k-sub-50", "10k-sub-45"],
  "relatedEvents": "valencia"
},

"10k-salida-del-sol-malaga": {
  "slugEs": "10k-salida-del-sol-malaga",
  "slugEn": "10k-salida-del-sol-malaga",
  "hasEn": false,
  "nameEs": "10K Salida del Sol Málaga",
  "nameEn": "",
  "city": "Málaga",
  "region": "Andalucía",
  "country": "ES",
  "distance": "10K",
  "distanceLabel": "10K",
  "distanceLabelEn": "10K",
  "distanceCategory": "10k",
  "dateMonth": 1,
  "dateText2026Es": "18 de enero de 2026",
  "dateText2026En": "",
  "startDate": "2026-01-18",
  "priceRange": "12-20",
  "currency": "EUR",
  "maxParticipants": 8000,
  "elevationEs": "Llano costero",
  "elevationEn": "",
  "heroImage": "https://images.pexels.com/photos/3076514/pexels-photo-3076514.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/3076520/pexels-photo-3076520.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "10K Salida del Sol Málaga 2026: inscripción, recorrido costero, consejos y toda la información sobre la carrera de 10K junto al mar en Málaga con 8.000 corredores.",
  "metaDescriptionEn": "",
  "descriptionEs": "La 10K Salida del Sol de Málaga es una de las carreras más singulares del sur de España, combinando la distancia reina del atletismo popular con un recorrido costero espectacular bañado por la luz del Mediterráneo. Cada mes de enero, cuando el resto de la península tiembla de frío, Málaga ofrece a los corredores la oportunidad de competir con temperaturas primaverales y un paisaje que mezcla el azul del mar con la blancura de la arquitectura andaluza.\n\nLa prueba se ha consolidado como la cita de referencia para abrir la temporada de running en Andalucía. Más de 8.000 corredores de toda España y del extranjero eligen Málaga para estrenarse en el nuevo año deportivo, atraídos por un circuito rápido junto al mar, una organización cuidada y la posibilidad de combinar deporte y turismo en una de las ciudades con mejor oferta gastronómica y cultural de la costa mediterránea.\n\nEl nombre de la carrera hace referencia al amanecer sobre el Mediterráneo que los corredores pueden contemplar durante los primeros kilómetros del recorrido. La salida, programada a primera hora de la mañana, permite disfrutar de los tonos dorados y rosados del cielo malagueño mientras se recorren las primeras calles junto al puerto. Es una experiencia sensorial única que trasciende lo puramente deportivo y que muchos participantes repiten año tras año.\n\nLa organización apuesta por la sostenibilidad y la responsabilidad social, eliminando los vasos de plástico de un solo uso en los avituallamientos y destinando parte de la recaudación a proyectos deportivos en barrios desfavorecidos de la ciudad. Además, colabora con establecimientos hoteleros de la zona para ofrecer paquetes especiales a los corredores que viajan desde fuera de Málaga, facilitando una experiencia completa de running y turismo.\n\nEl nivel competitivo de la carrera ha crecido notablemente en las últimas ediciones, atrayendo a atletas de élite nacionales que encuentran en el circuito malagueño las condiciones ideales para abrir la temporada con buenas marcas. La inscripción incluye camiseta técnica exclusiva con diseño inspirado en los amaneceres malagueños, dorsal con chip, medalla de finisher, bolsa del corredor y seguro deportivo completo.",
  "descriptionEn": "",
  "routeEs": "El recorrido de la 10K Salida del Sol arranca en el Paseo del Parque, junto al Ayuntamiento de Málaga, y se dirige hacia el este por el Paseo de los Curas hasta alcanzar el Paseo Marítimo Pablo Ruiz Picasso. Los corredores recorren el frente litoral con el Mediterráneo a su derecha, pasando junto a la Malagueta y las playas urbanas de la ciudad. El trazado gira a la altura de los Baños del Carmen y regresa por el mismo paseo marítimo hasta la zona portuaria, donde el tramo final atraviesa el Muelle Uno antes de alcanzar la meta de nuevo en el Paseo del Parque. El circuito es completamente llano sin desnivel apreciable y el asfalto del paseo marítimo está en excelente estado. Los avituallamientos se ubican en los kilómetros 3, 5 y 8.",
  "routeEn": "",
  "tipsEs": [
    "Aprovecha las temperaturas suaves de enero en Málaga para correr con ropa ligera de competición desde el primer kilómetro",
    "Lleva gafas de sol ya que la salida coincide con el amanecer y el reflejo del sol sobre el mar puede deslumbrar en los primeros tramos",
    "Hidrátate bien la noche anterior especialmente si vienes de una ciudad de interior ya que la humedad costera puede engañar",
    "Reserva alojamiento cerca del centro para ir andando a la salida y evitar problemas de aparcamiento en la zona del puerto",
    "Quédate después de la carrera a disfrutar de un desayuno malagueño con churros y chocolate en los bares del centro histórico"
  ],
  "tipsEn": [],
  "faqEs": [
    {"q": "¿Cuándo se celebra la 10K Salida del Sol Málaga 2026?", "a": "La 10K Salida del Sol Málaga 2026 se celebra el domingo 18 de enero. La salida está prevista a primera hora de la mañana, habitualmente entre las 8:30 y las 9:00, coincidiendo con el amanecer sobre el Mediterráneo."},
    {"q": "¿Qué tiempo hace en Málaga en enero para correr?", "a": "Enero en Málaga ofrece unas condiciones excepcionales para correr, con temperaturas medias de entre 10 y 17 grados y alta probabilidad de cielos despejados. Es uno de los mejores climas de España para competir en invierno."},
    {"q": "¿Cuánto cuesta la inscripción en la 10K Salida del Sol?", "a": "El precio de inscripción varía entre 12 y 20 euros dependiendo del periodo de registro. La tarifa reducida se aplica durante la inscripción anticipada que suele abrirse en octubre del año anterior. Las plazas están limitadas a 8.000 corredores."},
    {"q": "¿Es un recorrido llano la 10K Salida del Sol de Málaga?", "a": "Sí, el recorrido es completamente llano al discurrir íntegramente por el paseo marítimo y las avenidas costeras de Málaga. No hay ninguna cuesta ni desnivel significativo, lo que lo convierte en un circuito ideal para buscar buenas marcas."},
    {"q": "¿Se puede combinar la carrera con turismo en Málaga?", "a": "Por supuesto. Málaga ofrece una excelente oferta cultural con el Museo Picasso, la Alcazaba y el centro histórico, además de una gastronomía excepcional. Muchos corredores aprovechan el fin de semana para hacer turismo y disfrutar de los famosos espetos de sardinas y el pescaíto frito malagueño."}
  ],
  "faqEn": [],
  "relatedPlans": ["10k-principiantes", "10k-sub-50", "10k-sub-45"],
  "relatedEvents": "malaga"
}

};

console.log(JSON.stringify(data, null, 2));
