'use strict';

const data = {

"ccc-ultra-trail-mont-blanc": {
  "slugEs": "ccc-ultra-trail-mont-blanc",
  "slugEn": "ccc-ultra-trail-mont-blanc",
  "hasEn": true,
  "nameEs": "CCC Ultra-Trail du Mont-Blanc",
  "nameEn": "CCC Ultra-Trail du Mont-Blanc",
  "city": "Chamonix / Courmayeur",
  "region": "Alpes",
  "country": "ES",
  "distance": "101K",
  "distanceLabel": "101K",
  "distanceLabelEn": "101K",
  "distanceCategory": "trail",
  "dateMonth": 8,
  "dateText2026Es": "28 de agosto de 2026",
  "dateText2026En": "August 28, 2026",
  "startDate": "2026-08-28",
  "priceRange": "200-280",
  "currency": "EUR",
  "maxParticipants": 2500,
  "elevationEs": "D+ 6100m",
  "elevationEn": "D+ 6100m",
  "heroImage": "https://images.pexels.com/photos/2409022/pexels-photo-2409022.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/2409025/pexels-photo-2409025.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "CCC Ultra-Trail du Mont-Blanc 2026: guía completa con recorrido de 101K y 6100m D+, inscripción, consejos y todo sobre esta legendaria carrera alpina en Chamonix.",
  "metaDescriptionEn": "CCC Ultra-Trail du Mont-Blanc 2026: complete guide with 101K route and 6100m elevation gain, registration, tips and everything about this legendary Alpine race.",
  "descriptionEs": "La CCC (Courmayeur-Champex-Chamonix) es una de las pruebas más emblemáticas del festival Ultra-Trail du Mont-Blanc, considerado el campeonato del mundo oficioso del ultra-trail. Con 101 kilómetros de recorrido y un desnivel positivo acumulado de 6.100 metros, la CCC representa un desafío mayúsculo que atrae cada verano a 2.500 corredores de élite y aficionados de todo el planeta hasta el corazón de los Alpes.\n\nLa carrera parte de Courmayeur, la joya alpina del Valle de Aosta italiano, y atraviesa algunos de los paisajes más espectaculares de Europa antes de llegar a Chamonix-Mont-Blanc, en Francia. El recorrido cruza la frontera franco-italiana y pasa por territorio suizo, convirtiendo la prueba en una auténtica travesía internacional por tres países en una sola jornada de montaña. Los corredores se enfrentan a collados que superan los 2.500 metros de altitud, senderos técnicos tallados en la roca, bosques de alerces centenarios y praderas alpinas con vistas al macizo del Mont-Blanc, el techo de Europa occidental.\n\nDesde su creación en 2003, la CCC ha crecido hasta convertirse en la segunda carrera más demandada del festival UTMB, solo por detrás de la prueba reina de 171 kilómetros. El sistema de inscripción funciona mediante sorteo con puntos ITRA (International Trail Running Association), lo que garantiza que los participantes tengan un historial previo en carreras de montaña. Los corredores necesitan acumular un mínimo de puntos de carrera en los dos años previos para poder entrar en el sorteo, lo que eleva el nivel medio del pelotón.\n\nEl ambiente en Chamonix durante la semana del UTMB es incomparable. La ciudad se transforma en la capital mundial del trail running, con una feria del corredor multitudinaria, charlas técnicas, proyecciones de documentales de montaña y un ambiente festivo que envuelve cada rincón del pueblo. La llegada a la Place du Triangle de l'Amitié, con el arco de meta iluminado y miles de espectadores animando hasta altas horas de la madrugada, es una experiencia que marca la vida de cualquier corredor.\n\nEl tiempo límite para completar la CCC es de 26 horas y 15 minutos, aunque los élites suelen terminar en torno a las 10-11 horas. La carrera se disputa mayoritariamente de día, pero los corredores de la parte trasera del pelotón afrontarán tramos nocturnos que requieren frontal y equipamiento obligatorio. La meteorología alpina es impredecible: las temperaturas pueden oscilar entre los 30°C en los valles y los 0°C en los collados, con posibilidad de tormentas eléctricas, lluvia o incluso nieve en altitud.\n\nPara los corredores españoles, la CCC representa el salto definitivo al ultra-trail internacional. Muchos atletas españoles de primer nivel han brillado en esta prueba, y cada año crece la comunidad hispana que peregrina hasta Chamonix para vivir la experiencia UTMB.",
  "descriptionEn": "The CCC (Courmayeur-Champex-Chamonix) is one of the most iconic races within the Ultra-Trail du Mont-Blanc festival, widely regarded as the unofficial world championship of ultra-trail running. Covering 101 kilometres with a cumulative elevation gain of 6,100 metres, the CCC presents a formidable challenge that draws 2,500 elite and amateur runners from across the globe to the heart of the Alps every summer.\n\nThe race starts in Courmayeur, the stunning Alpine gem in Italy's Aosta Valley, and traverses some of Europe's most spectacular landscapes before finishing in Chamonix-Mont-Blanc, France. The route crosses the Franco-Italian border and passes through Swiss territory, making this a genuine international crossing through three countries in a single mountain day. Runners face cols exceeding 2,500 metres in altitude, technical rocky trails, ancient larch forests and Alpine meadows with sweeping views of the Mont-Blanc massif, the highest peak in Western Europe.\n\nSince its inception in 2003, the CCC has grown into the second most sought-after race in the UTMB festival, behind only the flagship 171-kilometre event. Registration works through a lottery system based on ITRA (International Trail Running Association) points, ensuring that participants have a proven track record in mountain races. Runners must accumulate a minimum number of race points over the previous two years to enter the draw, which raises the average standard of the field considerably.\n\nThe atmosphere in Chamonix during UTMB week is unrivalled. The town transforms into the global capital of trail running, hosting a massive runner expo, technical talks, mountain film screenings and a festive spirit that fills every corner. The finish at the Place du Triangle de l'Amitié, beneath the illuminated arch with thousands of spectators cheering deep into the night, is a life-defining moment for any runner.\n\nThe cut-off time for the CCC is 26 hours and 15 minutes, although elite runners typically finish in around 10-11 hours. The race runs mostly during daylight, but back-of-pack runners will face night sections requiring a headlamp and mandatory equipment. Alpine weather is unpredictable: temperatures can swing from 30°C in the valleys to 0°C on the cols, with the possibility of thunderstorms, rain or even snow at altitude.\n\nFor many international runners, the CCC represents the ultimate step into world-class ultra-trail. Each year the global community that makes the pilgrimage to Chamonix continues to grow, united by a shared passion for mountains and endurance.",
  "routeEs": "El recorrido de la CCC parte de Courmayeur (Italia) a las 9:00 de la mañana y se dirige hacia el sur bordeando el macizo del Mont-Blanc. Los primeros kilómetros transcurren por el Val Ferret italiano, un valle glaciar de belleza sobrecogedora. El primer gran reto es el Grand Col Ferret (2.537m), que marca la frontera entre Italia y Suiza. Desde allí se desciende al Val Ferret suizo hasta La Fouly, donde se encuentra el primer avituallamiento importante. La ruta continúa por Champex-Lac, un pintoresco pueblo junto a un lago alpino, antes de afrontar la subida a La Giète y el descenso técnico hacia Trient. El tramo final incluye la ascensión a la Tête aux Vents (2.132m) con vistas panorámicas al glaciar de Argentière, seguida de un descenso vertiginoso hasta La Flégère y el tramo final por el valle de Chamonix hasta la meta.",
  "routeEn": "The CCC route departs from Courmayeur (Italy) at 9:00 AM and heads south along the Mont-Blanc massif. The opening kilometres follow the Italian Val Ferret, a breathtaking glacial valley. The first major test is the Grand Col Ferret (2,537m), marking the border between Italy and Switzerland. From there runners descend into the Swiss Val Ferret to La Fouly, home to the first major aid station. The route continues through Champex-Lac, a picturesque village beside an Alpine lake, before tackling the climb to La Giète and the technical descent to Trient. The final stretch includes the ascent to Tête aux Vents (2,132m) with panoramic views of the Argentière glacier, followed by a steep descent to La Flégère and the closing kilometres through the Chamonix valley to the finish line.",
  "tipsEs": [
    "Entrena específicamente el descenso técnico: los 6.800m de desnivel negativo castigan más las piernas que las subidas",
    "Lleva ropa de capas y no subestimes el frío en los collados aunque sea agosto: las tormentas alpinas son frecuentes",
    "Practica la nutrición en carrera con antelación y calcula 250-300 calorías por hora para una prueba de esta duración",
    "Reserva alojamiento en Chamonix con meses de antelación ya que la semana del UTMB agota toda la oferta hotelera",
    "Estudia los horarios de corte de cada puesto de control y gestiona tu esfuerzo para no ir al límite en la primera mitad"
  ],
  "tipsEn": [
    "Train specifically for technical descents: the 6,800m of negative elevation punishes legs more than the climbs",
    "Carry layered clothing and do not underestimate the cold on the cols even in August: Alpine storms are frequent",
    "Practise race nutrition well in advance and plan for 250-300 calories per hour over this distance",
    "Book accommodation in Chamonix months ahead as UTMB week sells out every hotel in the valley",
    "Study the cut-off times at each checkpoint and manage your effort to avoid pushing too hard in the first half"
  ],
  "faqEs": [
    {"q": "¿Cómo funciona el sistema de inscripción de la CCC?", "a": "La inscripción se realiza mediante sorteo. Necesitas acumular un mínimo de puntos ITRA con carreras clasificatorias en los dos años previos. Una vez registrado en el sorteo, los resultados se publican en enero del año de la carrera."},
    {"q": "¿Cuál es el equipamiento obligatorio?", "a": "La organización exige un extenso listado que incluye mochila, frontal con pilas de repuesto, chaqueta impermeable con costuras termoselladas, pantalón largo, manta de supervivencia, silbato, vaso reutilizable, teléfono móvil y provisiones de reserva."},
    {"q": "¿Se puede hacer la CCC sin experiencia previa en ultra-trail?", "a": "No es recomendable. Los requisitos de puntos ITRA exigen haber completado carreras previas de montaña. Lo ideal es tener experiencia en pruebas de al menos 60-80 km con desnivel importante antes de intentar la CCC."},
    {"q": "¿Hay asistencia en el recorrido?", "a": "Sí, hay puestos de avituallamiento cada 10-15 km con comida caliente, agua, fruta y asistencia médica. Además, es posible dejar una bolsa de asistencia en determinados puntos para cambio de ropa o material."},
    {"q": "¿Qué tiempo medio emplean los corredores populares?", "a": "El corredor medio tarda entre 18 y 24 horas en completar la CCC. Los élites terminan en 10-11 horas mientras que el tiempo límite oficial es de 26 horas y 15 minutos."}
  ],
  "faqEn": [
    {"q": "How does the CCC registration system work?", "a": "Registration is by lottery. You need a minimum number of ITRA points from qualifying races over the previous two years. Once entered in the draw, results are published in January of the race year."},
    {"q": "What mandatory equipment is required?", "a": "The organisation requires an extensive kit list including a backpack, headlamp with spare batteries, waterproof jacket with taped seams, full-length trousers, survival blanket, whistle, reusable cup, mobile phone and reserve food supplies."},
    {"q": "Can I attempt the CCC without prior ultra-trail experience?", "a": "It is not recommended. The ITRA point requirements mean you must have completed previous mountain races. Ideally you should have experience in events of at least 60-80 km with significant elevation before attempting the CCC."},
    {"q": "Is there support along the course?", "a": "Yes, there are aid stations every 10-15 km offering hot food, water, fruit and medical assistance. You can also leave a drop bag at certain points for clothing or equipment changes."},
    {"q": "What is the average finishing time for recreational runners?", "a": "The average runner takes between 18 and 24 hours to complete the CCC. Elites finish in 10-11 hours while the official cut-off is 26 hours and 15 minutes."}
  ],
  "relatedPlans": ["trail-principiantes", "resistencia", "maraton-principiantes"],
  "relatedEvents": ""
},

"trail-costa-quebrada": {
  "slugEs": "trail-costa-quebrada",
  "slugEn": "trail-costa-quebrada",
  "hasEn": false,
  "nameEs": "Trail Costa Quebrada Cantabria",
  "nameEn": "",
  "city": "Santander",
  "region": "Cantabria",
  "country": "ES",
  "distance": "42K",
  "distanceLabel": "42K",
  "distanceLabelEn": "42K",
  "distanceCategory": "trail",
  "dateMonth": 4,
  "dateText2026Es": "11 de abril de 2026",
  "dateText2026En": "",
  "startDate": "2026-04-11",
  "priceRange": "35-55",
  "currency": "EUR",
  "maxParticipants": 2000,
  "elevationEs": "D+ 1200m",
  "elevationEn": "",
  "heroImage": "https://images.pexels.com/photos/3408354/pexels-photo-3408354.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/3408360/pexels-photo-3408360.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "Trail Costa Quebrada Cantabria 2026: inscripción, recorrido de 42K con 1200m D+ por acantilados y playas, consejos y guía completa de esta espectacular carrera costera.",
  "metaDescriptionEn": "",
  "descriptionEs": "El Trail Costa Quebrada es una de las carreras de trail más singulares de la Península Ibérica. Su recorrido discurre íntegramente por el Parque Natural de las Dunas de Liencres y la Costa Quebrada, un tramo litoral de Cantabria declarado Parque Geológico por la espectacularidad de sus formaciones rocosas, acantilados verticales, playas salvajes y arrecifes fósiles que datan de millones de años. Con 42 kilómetros de distancia y 1.200 metros de desnivel positivo acumulado, esta prueba ofrece un desafío técnico notable combinado con unos paisajes que dejan sin aliento.\n\nLa carrera se celebra cada primavera en la zona costera cercana a Santander, atrayendo a cerca de 2.000 corredores que buscan una experiencia de trail diferente a las pruebas de alta montaña habituales. Aquí no hay collados alpinos ni bosques de altura, sino acantilados batidos por el Cantábrico, senderos que serpentean entre formaciones de flysch, calas de arena dorada accesibles solo a pie y praderas costeras donde el viento del mar acompaña cada zancada.\n\nLo que distingue al Trail Costa Quebrada de otras pruebas es la variedad de su terreno. En apenas 42 kilómetros, los corredores pisan arena de playa, roca caliza, senderos de tierra entre eucaliptos, caminos herbosos sobre acantilados y tramos técnicos con cuerdas fijas en los pasos más expuestos. Las subidas no son largas pero sí constantes: el perfil se asemeja a una sierra de dientes con continuos sube y baja entre el nivel del mar y los puntos altos de los acantilados.\n\nLa organización ha sabido mantener el espíritu del trail puro a pesar del crecimiento de la prueba. Los avituallamientos se ubican en puntos estratégicos con productos locales como sobaos y quesada, dando un toque cántabro auténtico a la experiencia. El ambiente entre los participantes es cercano y festivo, muy alejado de la masificación de los grandes eventos urbanos.\n\nAbril es un mes excelente para correr en la costa cantábrica: las temperaturas son suaves (10-18°C), la vegetación está en plena explosión primaveral y la luz del Cantábrico ofrece un espectáculo cromático único. No obstante, la meteorología puede ser caprichosa y conviene estar preparado para lluvia, viento y cambios bruscos de temperatura.\n\nEl Trail Costa Quebrada ofrece también distancias más cortas (21K y 15K) para quienes buscan una primera experiencia en trail o prefieren una prueba menos exigente pero igualmente espectacular en cuanto a paisaje.",
  "descriptionEn": "",
  "routeEs": "El recorrido parte del pueblo de Liencres y se dirige hacia la costa por el Parque Natural de las Dunas, atravesando el sistema dunar más importante del norte de España. Los primeros kilómetros son relativamente llanos por pistas forestales antes de alcanzar la línea de acantilados. Desde allí, el trazado sigue la senda costera del GR-E9 con vistas permanentes al mar Cantábrico, pasando por playas como Portio, Cerrías y Somocuevas. El tramo central es el más técnico, con pasos entre formaciones de flysch y descensos a calas que exigen pie firme. Se atraviesa el corazón de la Costa Quebrada con sus arrecifes fósiles y formaciones caprichosas antes de girar hacia el interior por caminos rurales entre prados y bosques de eucalipto. El tramo final regresa a la costa para terminar en Liencres con el mar de fondo.",
  "routeEn": "",
  "tipsEs": [
    "Usa zapatillas de trail con buen agarre en roca mojada: los acantilados pueden estar resbaladizos por la humedad marina",
    "Lleva cortavientos ligero aunque haga sol: el viento en los acantilados puede ser muy intenso y enfría rápidamente",
    "Entrena los descensos técnicos en terreno irregular ya que hay tramos con roca suelta y escalones naturales",
    "Aprovecha los avituallamientos para reponer sales: la brisa marina y el viento aumentan la deshidratación sin que te des cuenta",
    "Disfruta del paisaje y no te obsesiones con el ritmo: los cambios constantes de terreno hacen inútil intentar mantener un paso uniforme"
  ],
  "tipsEn": [],
  "faqEs": [
    {"q": "¿Se puede participar sin experiencia previa en trail?", "a": "Sí, especialmente en las distancias cortas de 15K y 21K. La distancia de 42K requiere cierta experiencia en montaña y buena condición física, pero no es necesario tener un historial extenso en ultra-trail."},
    {"q": "¿Hay tramos peligrosos en el recorrido?", "a": "Algunos tramos junto a los acantilados requieren atención, especialmente si llueve. La organización instala cuerdas fijas y señalización en los pasos más expuestos, y hay voluntarios en los puntos técnicos."},
    {"q": "¿Cuál es el tiempo límite para la distancia de 42K?", "a": "El tiempo límite es de 8 horas, lo que permite un ritmo medio de unos 11:30 min/km incluyendo los tramos técnicos y los avituallamientos."},
    {"q": "¿Qué temperatura suele hacer en abril en la costa cántabra?", "a": "Las temperaturas oscilan entre los 10°C y los 18°C, aunque la sensación térmica puede ser menor por el viento marino. Es recomendable llevar capas y prever posibilidad de lluvia."},
    {"q": "¿Se necesitan bastones?", "a": "Los bastones están permitidos pero no son imprescindibles dado que el desnivel no es extremo. Si los usas, ten en cuenta que en los tramos de roca técnica pueden estorbar más que ayudar."}
  ],
  "faqEn": [],
  "relatedPlans": ["trail-principiantes", "resistencia", "maraton-principiantes"],
  "relatedEvents": ""
},

"trail-terres-ebre": {
  "slugEs": "trail-terres-ebre",
  "slugEn": "trail-terres-ebre",
  "hasEn": false,
  "nameEs": "Trail Terres de l'Ebre",
  "nameEn": "",
  "city": "Tortosa",
  "region": "Cataluña",
  "country": "ES",
  "distance": "55K",
  "distanceLabel": "55K",
  "distanceLabelEn": "55K",
  "distanceCategory": "trail",
  "dateMonth": 3,
  "dateText2026Es": "21 de marzo de 2026",
  "dateText2026En": "",
  "startDate": "2026-03-21",
  "priceRange": "40-60",
  "currency": "EUR",
  "maxParticipants": 1500,
  "elevationEs": "D+ 1800m",
  "elevationEn": "",
  "heroImage": "https://images.pexels.com/photos/1658505/pexels-photo-1658505.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/1658510/pexels-photo-1658510.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "Trail Terres de l'Ebre 2026: guía completa del recorrido de 55K con 1800m D+ por el Delta del Ebro y els Ports. Inscripción, consejos y preguntas frecuentes.",
  "metaDescriptionEn": "",
  "descriptionEs": "El Trail Terres de l'Ebre es una de las pruebas de montaña más completas del calendario catalán y una de las que ofrece mayor diversidad paisajística en toda España. Con 55 kilómetros y 1.800 metros de desnivel positivo, esta carrera atraviesa las comarcas del Baix Ebre y el Montsià, combinando la aridez de las sierras interiores con la exuberancia del valle del Ebro y los paisajes únicos de la Reserva de la Biosfera de les Terres de l'Ebre, declarada por la UNESCO en 2013.\n\nLa prueba tiene su base en Tortosa, la capital histórica del Baix Ebre, una ciudad milenaria que conserva su catedral gótica, el castillo de la Suda y un casco antiguo con siglos de historia. Desde allí, los corredores se adentran en un territorio que es un auténtico tesoro natural poco conocido fuera de Cataluña: montañas calizas cubiertas de pinos y carrascas, barrancos profundos tallados por el agua, miradores naturales sobre el curso del río Ebro y una fauna que incluye cabras hispánicas, águilas perdiceras y buitres leonados.\n\nLo que hace especial al Trail Terres de l'Ebre es la combinación de terrenos. Los corredores afrontan senderos forestales suaves, tramos de cresta con exposición, barrancos técnicos con escalones de roca, pistas agrícolas entre campos de olivos milenarios y caminos históricos que durante siglos comunicaron los pueblos del interior con el valle del Ebro. El desnivel se acumula de forma progresiva, con tres subidas principales que superan los 400 metros de ascenso cada una.\n\nLa organización, gestionada por clubes de montaña locales con profundo conocimiento del terreno, cuida especialmente la sostenibilidad del evento y la relación con el entorno natural. Los avituallamientos ofrecen productos kilómetro cero: aceite de oliva de las cooperativas locales, frutas de temporada del valle del Ebro, embutidos artesanales y coca de recapte, la torta tradicional de la zona.\n\nMarzo es una época ideal para correr en esta zona: las temperaturas son agradables (12-22°C), los almendros están en flor creando un espectáculo visual en las laderas, y las lluvias primaverales mantienen los barrancos con agua que aporta frescor a los tramos más exigentes. El viento de poniente puede ser un factor en las crestas, pero raramente resulta un problema serio.\n\nAdemás de la distancia reina de 55K, la organización ofrece una media maratón de montaña (25K) y una carrera corta de iniciación (12K), lo que permite participar a corredores de todos los niveles.",
  "descriptionEn": "",
  "routeEs": "La salida se realiza desde el centro histórico de Tortosa, junto a la catedral, y los primeros kilómetros ascienden rápidamente hacia la Serra del Coll de l'Alba por senderos empedrados y caminos forestales. La primera gran subida lleva a los corredores hasta el Mirador del Ebro (650m), con vistas panorámicas al río y al valle. Desde allí se desciende por un barranco técnico hasta la zona de Alfara de Carles, donde se encuentra el avituallamiento principal. El tramo central atraviesa la Serra de Cardó por senderos de cresta entre pinos y carrascas, alcanzando el punto más alto de la carrera (780m). La segunda mitad incluye un descenso largo hasta el valle, tramos entre campos de olivos centenarios y la última subida por la Serra del Montsianell antes del descenso final hacia Tortosa por el GR-7.",
  "routeEn": "",
  "tipsEs": [
    "Entrena en terreno mixto que combine pista forestal, sendero técnico y camino pedregoso para adaptarte a la variedad del recorrido",
    "Lleva protección solar aunque sea marzo: en las crestas expuestas el sol del Mediterráneo puede quemar incluso en primavera",
    "Planifica tu alimentación para un esfuerzo de 6-9 horas y no dependas solo de los avituallamientos",
    "Usa zapatillas con placa de roca o suela dura: los tramos de caliza suelta castigan mucho la planta del pie",
    "Recorre al menos parte del trazado antes de la carrera para familiarizarte con los barrancos técnicos y los tramos de cresta"
  ],
  "tipsEn": [],
  "faqEs": [
    {"q": "¿Se necesita experiencia previa en trail para la distancia de 55K?", "a": "Sí, se recomienda haber completado al menos una carrera de trail de 30-40 km antes de intentar los 55K. Para debutantes, la distancia de 25K es una opción excelente."},
    {"q": "¿Cómo es el marcaje del recorrido?", "a": "El recorrido está balizado con cintas reflectantes y señales cada pocos cientos de metros. En los cruces importantes hay voluntarios y la organización proporciona el track GPX descargable."},
    {"q": "¿Hay posibilidad de abandono en mitad de carrera?", "a": "Sí, en los avituallamientos principales hay servicio de evacuación para los corredores que decidan abandonar. La organización los traslada de vuelta a Tortosa."},
    {"q": "¿Cuál es el tiempo límite?", "a": "El tiempo límite para los 55K es de 11 horas, con horarios de corte intermedios en los avituallamientos principales que se publican antes de la carrera."},
    {"q": "¿Hay alojamiento disponible en Tortosa?", "a": "Tortosa cuenta con una buena oferta de hoteles, pensiones y apartamentos turísticos. El Parador de Turismo, ubicado en el castillo de la Suda, es una opción espectacular aunque conviene reservar con antelación."}
  ],
  "faqEn": [],
  "relatedPlans": ["trail-principiantes", "resistencia", "maraton-principiantes"],
  "relatedEvents": ""
},

"maraton-alpino-madrileno": {
  "slugEs": "maraton-alpino-madrileno",
  "slugEn": "maraton-alpino-madrileno",
  "hasEn": false,
  "nameEs": "Maratón Alpino Madrileño",
  "nameEn": "",
  "city": "Navacerrada",
  "region": "Comunidad de Madrid",
  "country": "ES",
  "distance": "42K",
  "distanceLabel": "42K",
  "distanceLabelEn": "42K",
  "distanceCategory": "trail",
  "dateMonth": 6,
  "dateText2026Es": "14 de junio de 2026",
  "dateText2026En": "",
  "startDate": "2026-06-14",
  "priceRange": "30-50",
  "currency": "EUR",
  "maxParticipants": 1000,
  "elevationEs": "D+ 2500m",
  "elevationEn": "",
  "heroImage": "https://images.pexels.com/photos/2116475/pexels-photo-2116475.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/2116480/pexels-photo-2116480.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "Maratón Alpino Madrileño 2026: guía completa de esta exigente prueba de 42K con 2500m D+ en la Sierra de Guadarrama. Inscripción, recorrido, consejos y FAQs.",
  "metaDescriptionEn": "",
  "descriptionEs": "El Maratón Alpino Madrileño (MAM) es la carrera de montaña más exigente y prestigiosa de la Comunidad de Madrid, y una de las pruebas de referencia del trail running español. Con 42 kilómetros de recorrido y un desnivel positivo acumulado de 2.500 metros por la cuerda principal de la Sierra de Guadarrama, esta carrera es un auténtico test de resistencia, técnica y fortaleza mental que pone a prueba incluso a los corredores más experimentados.\n\nDesde su primera edición, el MAM ha mantenido un espíritu de montañismo puro que lo diferencia de otras carreras más comerciales. La participación está limitada a 1.000 corredores, lo que garantiza una experiencia íntima y respetuosa con el entorno del Parque Nacional de la Sierra de Guadarrama. No hay grandes pantallas, ni música electrónica en meta, ni patrocinadores omnipresentes: aquí lo que importa es la montaña, el esfuerzo y la camaradería entre corredores que comparten una misma pasión.\n\nEl recorrido es demoledor. Los 2.500 metros de desnivel positivo se comprimen en una distancia de maratón, lo que significa subidas largas y empinadas seguidas de descensos técnicos y vertiginosos. Los corredores coronan cumbres emblemáticas de la sierra madrileña que habitualmente se conquistan con botas de montaña y mochila, pasando por cotas que superan los 2.200 metros de altitud. Los senderos son genuinos caminos de montaña: piedra suelta, canchales graníticos, tramos de pradera de altura y pasos entre piornales donde la orientación es fundamental.\n\nEl perfil de participantes del MAM refleja su carácter exigente: aquí no hay postureo ni disfraces. Los corredores que acuden son montañeros reconvertidos al trail, ultratraileros que buscan un entreno de calidad o atletas de pista que quieren medir su resistencia en un entorno real de alta montaña. El ambiente en los avituallamientos es familiar y solidario, con voluntarios veteranos que conocen la sierra como la palma de su mano.\n\nJunio ofrece condiciones de carrera favorables pero variables. Las mañanas suelen ser frescas (8-12°C en altura) pero el calor puede apretar en los valles a partir de mediodía. Las tormentas de verano son posibles por la tarde, especialmente en las zonas de cumbre, lo que obliga a llevar ropa impermeable como parte del equipo obligatorio.\n\nEl MAM es mucho más que una carrera: es una declaración de amor a la Sierra de Guadarrama y una tradición para cientos de corredores madrileños que cada junio se citan en Navacerrada para vivir una jornada de montaña inolvidable. Para muchos, completar el Maratón Alpino Madrileño es un objetivo más satisfactorio que cualquier maratón urbano.",
  "descriptionEn": "",
  "routeEs": "La salida se produce en el Puerto de Navacerrada (1.858m) con dirección a la cuerda larga de la Sierra de Guadarrama. Los primeros kilómetros ascienden por el camino Schmidt hasta la Bola del Mundo (2.265m), donde se sitúa la antigua estación de telecomunicaciones. Desde allí se recorre la cresta principal de la sierra hacia el suroeste, encadenando cumbres como Valdemartín, Cabeza de Hierro Mayor y la Maliciosa. El tramo central es el más técnico, con descensos por pedreras graníticas y canchales que exigen extrema precaución. Tras alcanzar el Collado de la Maliciosa se inicia un largo descenso por el valle antes de afrontar la última subida hacia el Puerto de la Fuenfría por la Calzada Romana. El tramo final desciende de nuevo hasta Navacerrada por senderos forestales entre pinos silvestres centenarios.",
  "routeEn": "",
  "tipsEs": [
    "Entrena las subidas largas con bastones ya que la mayoría de participantes los usan en los tramos de más pendiente",
    "Refuerza los cuádriceps con ejercicios excéntricos: los descensos por pedrera granítica son muy exigentes para las rodillas",
    "Lleva camiseta técnica de manga larga y cortavientos: en las cumbres a 2.200m puede hacer mucho frío incluso en junio",
    "Hidrátate abundantemente antes de la carrera ya que los avituallamientos en altura están más espaciados que en carreras urbanas",
    "Estudia el recorrido con antelación y haz al menos una salida larga por la cuerda de la sierra para conocer el terreno"
  ],
  "tipsEn": [],
  "faqEs": [
    {"q": "¿Es más duro que un maratón convencional?", "a": "Mucho más duro. Los 2.500 metros de desnivel positivo y el terreno técnico hacen que los tiempos habituales sean entre 2 y 3 veces superiores a los de un maratón en asfalto. El ganador suele tardar unas 4 horas."},
    {"q": "¿Se necesitan bastones?", "a": "No son obligatorios pero sí muy recomendables. Aproximadamente el 80% de los participantes usan bastones plegables, especialmente para las subidas largas y los descensos técnicos."},
    {"q": "¿Cuál es el tiempo límite?", "a": "El tiempo límite es de 10 horas con horarios de corte intermedios en varios puntos del recorrido. Se recomienda planificar el esfuerzo para no ir al límite en los primeros puestos de control."},
    {"q": "¿Hay riesgo de encontrar nieve en junio?", "a": "Es poco probable pero no imposible, especialmente en las caras norte de las cumbres más altas tras inviernos con mucha precipitación. La organización informa del estado del recorrido los días previos."},
    {"q": "¿Cómo llego al Puerto de Navacerrada?", "a": "La forma más cómoda es en coche propio (aparcamiento gratuito). También hay autobuses desde Madrid (línea 691 de Moncloa) aunque los horarios pueden no coincidir con la salida de la carrera a primera hora."}
  ],
  "faqEn": [],
  "relatedPlans": ["trail-principiantes", "resistencia", "maraton-principiantes"],
  "relatedEvents": ""
},

"trail-sierra-guadarrama": {
  "slugEs": "trail-sierra-guadarrama",
  "slugEn": "trail-sierra-guadarrama",
  "hasEn": false,
  "nameEs": "Trail Sierra de Guadarrama",
  "nameEn": "",
  "city": "Cercedilla",
  "region": "Comunidad de Madrid",
  "country": "ES",
  "distance": "30K",
  "distanceLabel": "30K",
  "distanceLabelEn": "30K",
  "distanceCategory": "trail",
  "dateMonth": 5,
  "dateText2026Es": "16 de mayo de 2026",
  "dateText2026En": "",
  "startDate": "2026-05-16",
  "priceRange": "25-40",
  "currency": "EUR",
  "maxParticipants": 1500,
  "elevationEs": "D+ 1500m",
  "elevationEn": "",
  "heroImage": "https://images.pexels.com/photos/3225529/pexels-photo-3225529.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/3225535/pexels-photo-3225535.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "Trail Sierra de Guadarrama 2026: guía del recorrido de 30K con 1500m D+ desde Cercedilla. Inscripción, ruta, consejos y todo sobre esta carrera en el Parque Nacional.",
  "metaDescriptionEn": "",
  "descriptionEs": "El Trail Sierra de Guadarrama es una de las carreras de montaña más populares de la zona centro de España y una puerta de entrada ideal al mundo del trail running para los corredores de la Comunidad de Madrid. Con 30 kilómetros de distancia y 1.500 metros de desnivel positivo acumulado, la prueba ofrece un equilibrio perfecto entre exigencia y accesibilidad, permitiendo que corredores con cierta preparación física puedan completarla sin necesidad de experiencia previa en ultradistancia.\n\nLa carrera tiene su epicentro en Cercedilla, un pueblo serrano a tan solo 60 kilómetros de Madrid que es punto de partida habitual de excursionistas y montañeros desde hace más de un siglo. La estación de Cercanías conecta directamente Cercedilla con la capital, lo que facilita enormemente la logística para los participantes que vienen de Madrid sin necesidad de coche.\n\nEl recorrido transcurre íntegramente dentro del Parque Nacional de la Sierra de Guadarrama, el espacio natural protegido más importante de la región central de España. Los senderos cruzan bosques de pino silvestre centenarios cuyos troncos rojizos crean una atmósfera casi mágica, praderas de alta montaña donde pacen vacas y caballos en libertad, arroyos de agua cristalina que descienden de las cumbres y miradores naturales con vistas que en días claros alcanzan hasta la Sierra de Gredos al oeste y las llanuras castellanas al sur.\n\nEl perfil del Trail Sierra de Guadarrama es ondulado y exigente pero manejable. Las subidas son progresivas y los descensos, aunque técnicos en algunos tramos, no presentan la dificultad extrema de las pedreras graníticas de crestas más altas. Esto convierte a la carrera en un escalón formativo ideal para quienes aspiran a pruebas más largas como el Maratón Alpino Madrileño o las carreras del circuito UTMB.\n\nLa organización, vinculada a los clubes de montaña locales de Cercedilla, cuida especialmente el aspecto medioambiental del evento. La filosofía es clara: que el paso de los corredores deje la mínima huella posible en un entorno de Parque Nacional. Los vasos reutilizables son obligatorios, no se permiten envases de un solo uso y la señalización se retira completamente tras la carrera.\n\nMayo es el mes perfecto para esta prueba: las temperaturas son suaves (10-20°C), los días son largos y luminosos, y la sierra está en su momento de mayor esplendor con los piornos en flor tiñendo de amarillo las laderas. El nivel de los participantes es variado, desde corredores populares que buscan su primer reto en montaña hasta atletas locales de buen nivel que utilizan la carrera como entreno específico para pruebas más exigentes.\n\nAdemás de los 30K, se ofrece una distancia de iniciación de 15K que comparte parte del recorrido y es perfecta para quienes dan sus primeros pasos en el trail running.",
  "descriptionEn": "",
  "routeEs": "La salida se realiza desde el centro de Cercedilla y los primeros kilómetros ascienden por la Calzada Romana, el antiguo camino empedrado que conectaba la meseta con Segovia a través del Puerto de la Fuenfría. Tras alcanzar la Pradera de los Corralillos, el recorrido gira hacia el oeste por senderos forestales entre pinos hasta el mirador de la Bola del Mundo. El tramo central sigue la Senda Herreros con varias subidas y bajadas por el corazón del pinar antes de alcanzar el punto más alto del recorrido en las inmediaciones del Puerto de la Fuenfría (1.796m). La segunda mitad desciende por el valle del río de la Venta hacia las Dehesas de Cercedilla, pasando por fuentes naturales y áreas recreativas. El último tramo es una bajada rápida por caminos anchos que devuelven a los corredores al centro de Cercedilla.",
  "routeEn": "",
  "tipsEs": [
    "Si vienes desde Madrid en Cercanías, toma el tren temprano y lleva la ropa de carrera puesta para simplificar la logística",
    "Usa zapatillas de trail con buena amortiguación: los descensos por sendero forestal con piedra suelta son largos y constantes",
    "Lleva vaso reutilizable obligatorio: no te darán vasos desechables en los avituallamientos del Parque Nacional",
    "Hidrátate bien la noche anterior y desayuna al menos 2 horas antes de la salida con alimentos que ya hayas probado en entrenamientos",
    "Haz al menos una salida larga por Cercedilla antes de la carrera para conocer los senderos y adaptar tus piernas al terreno"
  ],
  "tipsEn": [],
  "faqEs": [
    {"q": "¿Es apta para principiantes en trail?", "a": "Los 30K requieren cierta preparación en montaña, pero la distancia de 15K es perfecta para debutantes. Si puedes correr 10K en asfalto cómodamente y tienes algo de experiencia en senderos, la versión corta es totalmente accesible."},
    {"q": "¿Cómo llego a Cercedilla sin coche?", "a": "La línea C-8b de Cercanías Madrid conecta Atocha y Chamartín con Cercedilla en aproximadamente 1 hora y 15 minutos. Los trenes empiezan a funcionar desde las 5:30 los sábados."},
    {"q": "¿Hay guardarropa o consigna?", "a": "Sí, la organización habilita un guardarropa en la zona de salida-meta donde puedes dejar una bolsa con ropa de cambio y objetos personales."},
    {"q": "¿Cuál es el tiempo límite para los 30K?", "a": "El tiempo límite es de 7 horas, lo que permite un ritmo medio cómodo de unos 14 min/km incluyendo los tramos de subida y los avituallamientos."},
    {"q": "¿Se necesitan bastones?", "a": "Los bastones están permitidos y son útiles en las subidas más pronunciadas, pero muchos corredores completan la prueba sin ellos. Si no estás acostumbrado a usarlos, es mejor no estrenarlos el día de la carrera."}
  ],
  "faqEn": [],
  "relatedPlans": ["trail-principiantes", "resistencia", "maraton-principiantes"],
  "relatedEvents": ""
}

};

console.log(JSON.stringify(data, null, 2));
