'use strict';

const data = {

"media-maraton-valencia": {
  "slugEs": "media-maraton-valencia",
  "slugEn": "valencia-half-marathon",
  "hasEn": true,
  "nameEs": "Medio Maratón Valencia Trinidad Alfonso",
  "nameEn": "Valencia Trinidad Alfonso Half Marathon",
  "city": "Valencia",
  "region": "Comunidad Valenciana",
  "country": "ES",
  "distance": "21.097K",
  "distanceLabel": "Media Maratón",
  "distanceLabelEn": "Half Marathon",
  "distanceCategory": "media-maraton",
  "dateMonth": 10,
  "dateText2026Es": "25 de octubre de 2026",
  "dateText2026En": "October 25, 2026",
  "startDate": "2026-10-25",
  "priceRange": "35-55",
  "currency": "EUR",
  "maxParticipants": 18000,
  "elevationEs": "Llano, desnivel acumulado inferior a 20 metros",
  "elevationEn": "Flat, cumulative elevation gain under 20 meters",
  "heroImage": "https://images.pexels.com/photos/3764958/pexels-photo-3764958.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/3764011/pexels-photo-3764011.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "Medio Maratón Valencia 2026: guía completa con inscripción, recorrido llano y rápido, consejos y FAQ. Corre el 25 de octubre en uno de los circuitos más veloces del mundo.",
  "metaDescriptionEn": "Valencia Half Marathon 2026: full guide with registration, flat and fast course, tips and FAQ. Run October 25 on one of the world's fastest half marathon circuits.",
  "descriptionEs": "El Medio Maratón Valencia Trinidad Alfonso se ha consolidado como una de las pruebas de medio fondo más prestigiosas del panorama internacional, atrayendo cada año a corredores de élite y populares de más de 100 países. Celebrado en la ciudad del Turia desde hace más de tres décadas, este evento ha sido escenario de múltiples récords mundiales y nacionales gracias a un circuito extraordinariamente llano y a unas condiciones climáticas que en octubre rozan la perfección para el rendimiento deportivo.\n\nValencia se ha ganado a pulso el sobrenombre de Ciudad del Running, y el medio maratón es la joya de su corona. La prueba forma parte del circuito World Athletics Gold Label, la máxima categoría otorgada por la federación internacional, lo que garantiza unos estándares de organización, cronometraje y servicios al corredor de primer nivel mundial. Cada edición supera a la anterior en participación y en la calidad de las marcas registradas, consolidando Valencia como destino obligado para quienes buscan batir sus récords personales en la distancia de 21 kilómetros.\n\nEl ambiente que se vive en las calles valencianas el día de la carrera es sencillamente espectacular. Más de 200.000 personas se congregan a lo largo del recorrido para animar a los participantes, creando un corredor humano que empuja a los corredores desde el primer kilómetro hasta la emblemática llegada a la Ciudad de las Artes y las Ciencias, uno de los marcos arquitectónicos más impresionantes del atletismo mundial. Las bandas de música, los grupos de animación y las pantallas gigantes en los puntos estratégicos contribuyen a mantener la motivación durante toda la prueba.\n\nLa organización del medio maratón cuida especialmente la experiencia del corredor popular. La feria del corredor, ubicada en el complejo ferial de Feria Valencia, se extiende durante tres días con decenas de stands de marcas deportivas, nutrición y turismo. La entrega de dorsales es ágil y eficiente, y la bolsa del corredor incluye productos de calidad seleccionados por los patrocinadores. Los avituallamientos durante la carrera ofrecen agua, isotónico y geles energéticos en puntos perfectamente señalizados.\n\nEl clima de Valencia a finales de octubre es ideal para correr: temperaturas entre 14 y 20 grados, humedad moderada y viento prácticamente inexistente en el trazado urbano protegido por los edificios. Estas condiciones, combinadas con el perfil completamente plano del circuito, explican por qué miles de corredores eligen Valencia para intentar sus mejores marcas en media maratón. No es casualidad que aquí se hayan logrado tiempos que han reescrito los libros de récords del atletismo.\n\nLa inscripción se abre habitualmente en diciembre del año anterior y las plazas más económicas se agotan en pocas semanas, por lo que se recomienda registrarse cuanto antes. El pago incluye dorsal con chip, camiseta técnica oficial, medalla finisher, bolsa del corredor y acceso a la zona de recuperación post-meta con frutas, isotónico y fisioterapia gratuita.",
  "descriptionEn": "The Valencia Trinidad Alfonso Half Marathon has established itself as one of the most prestigious half marathons in the world, attracting elite and amateur runners from over 100 countries each year. Held in the city on the Turia River for more than three decades, this event has been the stage for multiple world and national records thanks to an extraordinarily flat circuit and October weather conditions that are close to perfect for peak athletic performance.\n\nValencia has rightfully earned the nickname City of Running, and the half marathon is the crown jewel of its racing calendar. The event holds World Athletics Gold Label status, the highest category awarded by the international federation, which guarantees world-class standards in organization, timing, and runner services. Each edition surpasses the last in participation numbers and the quality of times recorded, cementing Valencia as a must-visit destination for runners seeking to smash their personal bests over the 21-kilometer distance.\n\nThe atmosphere on Valencia's streets on race day is simply spectacular. Over 200,000 spectators line the course to cheer on participants, creating a human corridor that propels runners from the very first kilometer to the iconic finish line at the City of Arts and Sciences, one of the most impressive architectural settings in world athletics. Live bands, cheer squads, and giant screens at strategic points help maintain motivation throughout the race.\n\nThe organization pays special attention to the experience of everyday runners. The runners' expo, held at the Feria Valencia convention center, spans three days with dozens of booths from sports brands, nutrition companies, and tourism boards. Bib pickup is quick and efficient, and the runner's bag includes quality products selected by sponsors. On-course aid stations offer water, electrolyte drinks, and energy gels at perfectly marked locations.\n\nValencia's climate in late October is ideal for running: temperatures between 14 and 20 degrees Celsius, moderate humidity, and virtually no wind on the urban course sheltered by buildings. These conditions, combined with the completely flat course profile, explain why thousands of runners choose Valencia to attempt their best half marathon times. It is no coincidence that times recorded here have rewritten the record books of world athletics.\n\nRegistration typically opens in December of the previous year, and the cheapest entry tiers sell out within weeks, so early sign-up is strongly recommended. The entry fee includes a timed bib, official technical shirt, finisher medal, runner's bag, and access to the post-finish recovery zone with fruit, electrolyte drinks, and free physiotherapy.",
  "routeEs": "El recorrido del Medio Maratón Valencia es un circuito urbano prácticamente llano que discurre por las principales avenidas y puentes de la ciudad. La salida se da en la Alameda, junto al antiguo cauce del río Turia, y los primeros kilómetros transcurren por amplias avenidas que permiten una salida fluida pese a los 18.000 participantes. El trazado serpentea por el centro histórico pasando cerca de la Plaza del Ayuntamiento, el Mercado Central y las Torres de Serranos antes de enfilar hacia el sur por la Avenida del Puerto. Los kilómetros centrales recorren zonas residenciales con buen asfalto y sombra parcial de los árboles. A partir del kilómetro 15, el circuito gira hacia la espectacular Ciudad de las Artes y las Ciencias, donde la recta final de casi dos kilómetros junto a los edificios de Calatrava ofrece un escenario inolvidable. Los avituallamientos se sitúan cada 5 kilómetros con agua, isotónico y esponjas.",
  "routeEn": "The Valencia Half Marathon course is a virtually flat urban circuit running through the city's main avenues and bridges. The start takes place at the Alameda, alongside the former Turia riverbed, and the opening kilometers follow wide boulevards that allow a smooth start despite the 18,000 participants. The route winds through the historic center past the Town Hall Square, the Central Market, and the Serranos Towers before heading south along Avenida del Puerto. The middle kilometers pass through residential areas with good tarmac and partial tree shade. From kilometer 15 onward, the course turns toward the spectacular City of Arts and Sciences, where the nearly two-kilometer finishing straight alongside Calatrava's buildings provides an unforgettable setting. Aid stations are placed every 5 kilometers offering water, electrolyte drinks, and sponges.",
  "tipsEs": [
    "Reserva alojamiento cerca de la Ciudad de las Artes y las Ciencias para llegar caminando a la meta y evitar el transporte el día de la carrera",
    "Visita la feria del corredor el jueves o viernes para evitar las aglomeraciones del sábado y recoge tu dorsal con tranquilidad",
    "Aprovecha el perfil llano para mantener un ritmo constante desde el primer kilómetro sin salir demasiado rápido",
    "Lleva manga corta y pantalón corto: aunque octubre puede amanecer fresco, la temperatura sube rápidamente durante la carrera",
    "Marca un punto de encuentro con familia o amigos en la zona de meta de la Ciudad de las Artes para celebrar juntos al terminar"
  ],
  "tipsEn": [
    "Book accommodation near the City of Arts and Sciences so you can walk to the finish area and avoid transport on race day",
    "Visit the runners' expo on Thursday or Friday to avoid Saturday crowds and pick up your bib at a relaxed pace",
    "Take advantage of the flat profile to maintain a steady pace from kilometer one without going out too fast",
    "Wear short sleeves and shorts: although October mornings can feel cool, the temperature rises quickly during the race",
    "Arrange a meeting point with family or friends in the finish zone at the City of Arts to celebrate together after crossing the line"
  ],
  "faqEs": [
    {"q": "¿Es el Medio Maratón de Valencia un circuito rápido?", "a": "Sí, es considerado uno de los circuitos de media maratón más rápidos del mundo. Su perfil completamente llano, el excelente asfalto y las condiciones climáticas de octubre lo convierten en el escenario ideal para batir récords personales."},
    {"q": "¿Cuándo se abren las inscripciones?", "a": "Las inscripciones suelen abrirse en diciembre del año anterior. Los tramos de precio más económicos se agotan en pocas semanas, por lo que se recomienda inscribirse lo antes posible para asegurar la tarifa más baja."},
    {"q": "¿Hay servicio de guardaequipaje?", "a": "Sí, la organización ofrece un servicio de guardaequipaje gratuito cerca de la zona de salida. Se entrega una bolsa específica con el dorsal del corredor para facilitar la recogida tras la carrera."},
    {"q": "¿Qué transporte público hay para llegar a la salida?", "a": "La zona de salida en la Alameda es accesible en metro (líneas 3 y 5, estación Alameda) y en numerosas líneas de autobús de la EMT. La organización recomienda evitar el coche particular debido a los cortes de tráfico."},
    {"q": "¿Se puede correr con auriculares?", "a": "Sí, está permitido correr con auriculares aunque la organización recomienda llevar el volumen bajo para escuchar las indicaciones de los voluntarios y disfrutar del ambiente de animación en las calles."}
  ],
  "faqEn": [
    {"q": "Is the Valencia Half Marathon a fast course?", "a": "Yes, it is considered one of the fastest half marathon courses in the world. Its completely flat profile, excellent tarmac, and October weather conditions make it the ideal setting for achieving personal bests."},
    {"q": "When does registration open?", "a": "Registration usually opens in December of the previous year. The cheapest entry tiers sell out within weeks, so signing up early is recommended to secure the lowest price."},
    {"q": "Is there a bag drop service?", "a": "Yes, the organization provides a free bag drop service near the start area. A specific bag with the runner's bib number is provided for easy collection after the race."},
    {"q": "What public transport options are there to reach the start?", "a": "The start area at the Alameda is accessible by metro (lines 3 and 5, Alameda station) and numerous EMT bus routes. The organization recommends avoiding private cars due to road closures."},
    {"q": "Can I run with headphones?", "a": "Yes, headphones are allowed, although the organization recommends keeping the volume low to hear volunteer instructions and enjoy the lively street atmosphere."}
  ],
  "relatedPlans": ["media-maraton-principiantes", "media-maraton-sub-1-45", "media-maraton-sub-1-30"],
  "relatedEvents": "valencia"
},

"media-maraton-madrid": {
  "slugEs": "media-maraton-madrid",
  "slugEn": "media-maraton-madrid",
  "hasEn": false,
  "nameEs": "Movistar Medio Maratón de Madrid",
  "nameEn": "",
  "city": "Madrid",
  "region": "Comunidad de Madrid",
  "country": "ES",
  "distance": "21.097K",
  "distanceLabel": "Media Maratón",
  "distanceLabelEn": "Half Marathon",
  "distanceCategory": "media-maraton",
  "dateMonth": 3,
  "dateText2026Es": "29 de marzo de 2026",
  "dateText2026En": "",
  "startDate": "2026-03-29",
  "priceRange": "30-50",
  "currency": "EUR",
  "maxParticipants": 25000,
  "elevationEs": "Ondulado, desnivel acumulado aproximado de 120 metros",
  "elevationEn": "",
  "heroImage": "https://images.pexels.com/photos/2199590/pexels-photo-2199590.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/2168292/pexels-photo-2168292.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "Medio Maratón de Madrid 2026: inscripción, recorrido por el centro histórico, consejos y FAQ. Corre el 29 de marzo con 25.000 participantes por las calles más emblemáticas de la capital.",
  "metaDescriptionEn": "",
  "descriptionEs": "El Movistar Medio Maratón de Madrid es una de las pruebas atléticas más importantes del calendario deportivo español y un evento que cada año reúne a 25.000 corredores en las calles de la capital. Organizado por el Ayuntamiento de Madrid en colaboración con la Federación Madrileña de Atletismo, este medio maratón combina un recorrido espectacular por los monumentos más icónicos de la ciudad con una organización de nivel internacional que le ha valido la categoría World Athletics Gold Label.\n\nLa prueba se celebra habitualmente en el último fin de semana de marzo, coincidiendo con el inicio de la primavera madrileña, cuando las temperaturas oscilan entre los 8 y los 18 grados, ofreciendo condiciones muy favorables para correr. Sin embargo, a diferencia de circuitos completamente llanos como Valencia, el medio maratón de Madrid presenta un perfil ondulado con varias subidas y bajadas que ponen a prueba la gestión del ritmo de los participantes, especialmente en los repechos de la zona de Moncloa y la subida hacia el Templo de Debod.\n\nEl punto de salida se sitúa junto al estadio Santiago Bernabéu en el Paseo de la Castellana, uno de los bulevares más anchos de Europa, lo que permite una salida cómoda incluso para el enorme pelotón de corredores. El recorrido desciende por la Castellana hasta Cibeles, gira por la Gran Vía y atraviesa el Madrid de los Austrias antes de llegar al tramo final en el Parque del Retiro, donde los corredores cruzan la meta en un entorno natural de enorme belleza paisajística.\n\nLa feria del corredor se celebra en el recinto ferial de IFEMA y es una de las más grandes de España, con cientos de expositores de material deportivo, nutrición, fisioterapia y turismo activo. La recogida de dorsales está perfectamente organizada por orden alfabético y el proceso raramente supera los diez minutos de espera. La bolsa del corredor incluye la camiseta técnica oficial, productos de los patrocinadores y descuentos en tiendas deportivas de la ciudad.\n\nUno de los aspectos más valorados por los participantes es el extraordinario ambiente que se vive en las calles madrileñas durante la carrera. Los vecinos salen a los balcones, las peñas despliegan pancartas de ánimo y los puntos de animación con música en directo se suceden cada pocos kilómetros, creando una atmósfera festiva que ayuda a superar los momentos más duros de la prueba. El paso por la Puerta del Sol, la Plaza Mayor y el Palacio Real ofrece estampas que los corredores recuerdan durante años.\n\nLa meta se ubica en el interior del Parque del Retiro, junto al Estanque Grande, donde los finishers reciben su medalla conmemorativa, una botella de agua, fruta y acceso a la zona de recuperación con servicios de fisioterapia y estiramientos guiados. El transporte público gratuito el día de la carrera facilita los desplazamientos de los participantes y sus acompañantes.",
  "descriptionEn": "",
  "routeEs": "El recorrido del Medio Maratón de Madrid parte del Paseo de la Castellana a la altura del Santiago Bernabéu y desciende por esta emblemática avenida durante los primeros cinco kilómetros hasta la Plaza de Cibeles. Aquí el trazado gira hacia el oeste por la calle Alcalá y la Gran Vía, ofreciendo vistas espectaculares de los edificios históricos de la capital. Tras atravesar la Plaza de España, el circuito sube ligeramente hacia Moncloa y el Templo de Debod, el tramo más exigente de la carrera con una pendiente sostenida de casi un kilómetro. El descenso posterior por la Cuesta de San Vicente conduce a los corredores hasta el Palacio Real y la Catedral de la Almudena. Los últimos kilómetros discurren por el Madrid de los Austrias, la Puerta del Sol y la calle Alcalá antes de entrar en el Parque del Retiro por la Puerta de Alcalá. La meta se sitúa junto al Estanque del Retiro en una recta final sobre tierra compactada.",
  "routeEn": "",
  "tipsEs": [
    "Gestiona bien las subidas de Moncloa y el Templo de Debod: baja ligeramente el ritmo para no pagar el esfuerzo en los últimos kilómetros",
    "Aprovecha el metro gratuito el día de la carrera para llegar a la zona de salida en Castellana sin agobios de aparcamiento",
    "Abrígate con una camiseta vieja de descarte para la espera en la salida: las mañanas de marzo en Madrid pueden ser frías",
    "Hidrátate en todos los avituallamientos porque el aire seco de Madrid deshidrata más de lo que parece",
    "Planifica ver la carrera desde Cibeles o Sol si vienes como acompañante: son los puntos con mejor ambiente y acceso"
  ],
  "tipsEn": [],
  "faqEs": [
    {"q": "¿El Medio Maratón de Madrid es llano?", "a": "No, presenta un perfil ondulado con un desnivel acumulado de unos 120 metros. Las subidas más notables están en la zona de Moncloa y el Templo de Debod, mientras que los primeros kilómetros por la Castellana son en descenso."},
    {"q": "¿Hay límite de tiempo para completar la prueba?", "a": "Sí, el tiempo límite oficial es de 2 horas y 45 minutos. Los corredores que superen este tiempo deberán incorporarse a la acera y la organización no garantiza los servicios de avituallamiento ni cierre de tráfico."},
    {"q": "¿Dónde se recoge el dorsal?", "a": "Los dorsales se recogen en la feria del corredor en IFEMA (Feria de Madrid), que abre de jueves a sábado. No es posible recoger el dorsal el día de la carrera, así que es imprescindible pasar por IFEMA antes del domingo."},
    {"q": "¿El transporte público es gratuito el día de la carrera?", "a": "Sí, el Ayuntamiento de Madrid habilita transporte público gratuito para los corredores acreditados con su dorsal el día de la prueba, incluyendo metro, autobús y cercanías dentro de la zona A."},
    {"q": "¿Se puede participar en silla de ruedas?", "a": "Sí, el Medio Maratón de Madrid cuenta con una categoría de silla de ruedas que sale unos minutos antes del pelotón principal. Los participantes deben inscribirse específicamente en esta categoría."}
  ],
  "faqEn": [],
  "relatedPlans": ["media-maraton-principiantes", "media-maraton-sub-1-45", "media-maraton-sub-1-30"],
  "relatedEvents": "madrid"
},

"media-maraton-barcelona": {
  "slugEs": "media-maraton-barcelona",
  "slugEn": "media-maraton-barcelona",
  "hasEn": false,
  "nameEs": "Mitja Marató Barcelona",
  "nameEn": "",
  "city": "Barcelona",
  "region": "Cataluña",
  "country": "ES",
  "distance": "21.097K",
  "distanceLabel": "Media Maratón",
  "distanceLabelEn": "Half Marathon",
  "distanceCategory": "media-maraton",
  "dateMonth": 2,
  "dateText2026Es": "8 de febrero de 2026",
  "dateText2026En": "",
  "startDate": "2026-02-08",
  "priceRange": "35-55",
  "currency": "EUR",
  "maxParticipants": 15000,
  "elevationEs": "Prácticamente llano, desnivel acumulado inferior a 40 metros",
  "elevationEn": "",
  "heroImage": "https://images.pexels.com/photos/3766211/pexels-photo-3766211.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/3766217/pexels-photo-3766217.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "Mitja Marató Barcelona 2026: inscripción, recorrido por la costa y el Eixample, consejos y preguntas frecuentes. Corre el 8 de febrero con 15.000 participantes junto al Mediterráneo.",
  "metaDescriptionEn": "",
  "descriptionEs": "La Mitja Marató de Barcelona es una de las pruebas de medio fondo más consolidadas de España y un referente en el circuito internacional de medias maratones urbanas. Celebrada cada mes de febrero, esta carrera ofrece una combinación única de recorrido urbano espectacular, clima suave invernal y una organización meticulosa que la ha convertido en cita obligada para miles de corredores nacionales e internacionales que buscan un buen resultado en la primera mitad de la temporada de carreras.\n\nBarcelona es una ciudad que respira deporte y cultura a partes iguales, y la Mitja Marató aprovecha esta identidad para ofrecer un recorrido que funciona como un tour arquitectónico y paisajístico de primer nivel. Los participantes recorren algunos de los enclaves más reconocibles de la Ciudad Condal, desde las amplias avenidas del Eixample hasta el paseo marítimo con vistas al Mediterráneo, pasando por la zona del Port Olímpic y la Barceloneta. Es difícil encontrar otra media maratón en Europa que combine de forma tan armoniosa patrimonio cultural y paisaje costero.\n\nEl perfil del circuito es prácticamente llano, con un desnivel acumulado que apenas supera los 40 metros, lo que lo convierte en un trazado rápido y apto para corredores de todos los niveles. Las únicas variaciones de pendiente son suaves transiciones en los pasos elevados y algún pequeño repecho en la zona del Fòrum, pero nada que altere significativamente el ritmo de carrera. Esta configuración, unida a las temperaturas de febrero que suelen oscilar entre los 8 y los 15 grados, hace de la Mitja Marató Barcelona una excelente opción para debutar en la distancia o para buscar una marca personal.\n\nLa organización, a cargo de RPM Racing, cuenta con amplia experiencia en la gestión de grandes eventos deportivos en la capital catalana. La feria del corredor se celebra en un recinto céntrico de fácil acceso y ofrece una amplia oferta de marcas deportivas, nutrición y servicios para runners. Los avituallamientos durante la carrera están perfectamente distribuidos cada 5 kilómetros con agua, bebida isotónica y frutas, y los puntos de animación incluyen batucadas, grupos de música y escuadrones de voluntarios que animan incansablemente a los participantes.\n\nLa Mitja Marató también destaca por su compromiso con la sostenibilidad: los vasos de plástico han sido sustituidos por vasos compostables, se minimiza el uso de botellas individuales y la camiseta técnica oficial está fabricada con materiales reciclados. La medalla finisher, de diseño diferente cada año, se ha convertido en objeto de coleccionismo entre los corredores habituales de la prueba.\n\nBarcelona ofrece además una infraestructura hotelera y de transporte de primera categoría, lo que facilita enormemente la logística para los participantes que viajan desde fuera de la ciudad. El aeropuerto de El Prat, la red de metro y las líneas de autobús cubren perfectamente las necesidades de desplazamiento tanto el día previo como el día de la carrera. Muchos corredores aprovechan el fin de semana para combinar la prueba con una escapada turística y gastronómica por la ciudad.",
  "descriptionEn": "",
  "routeEs": "El recorrido de la Mitja Marató de Barcelona parte de la Avenida María Cristina, al pie de la fuente de Montjuïc, y desciende suavemente hacia la Gran Vía de les Corts Catalanes, una de las arterias más amplias de la ciudad. Los primeros kilómetros transcurren por el Eixample, con el trazado en cuadrícula que caracteriza esta zona de Barcelona, antes de girar hacia el mar por el Passeig de Gràcia. El circuito recorre el frente marítimo pasando por el Port Olímpic, la playa de la Barceloneta y el Moll de la Fusta, ofreciendo vistas abiertas al Mediterráneo durante varios kilómetros. La parte central del recorrido atraviesa la zona del Fòrum y Diagonal Mar antes de regresar por la Avenida Diagonal. Los últimos kilómetros discurren nuevamente por el Eixample hasta alcanzar la meta en la Avenida María Cristina. El asfalto está en buen estado y las calles son lo suficientemente anchas para evitar atascos incluso en los tramos más concurridos.",
  "routeEn": "",
  "tipsEs": [
    "Febrero en Barcelona puede ser ventoso junto al mar: lleva una capa fina cortavientos por si acaso y descártala si hace calor al correr",
    "Colócate en tu cajón de salida según el ritmo declarado en la inscripción para evitar empezar frenado entre corredores más lentos",
    "Aprovecha los kilómetros junto al mar para relajar los hombros y disfrutar del paisaje: es la parte más bonita del recorrido",
    "Hidrátate bien el día anterior ya que la brisa marina puede enmascarar la sensación de sed durante la carrera",
    "Reserva restaurante para la comida post-carrera con antelación: la Barceloneta y el Born se llenan de corredores celebrando"
  ],
  "tipsEn": [],
  "faqEs": [
    {"q": "¿Cuándo se celebra la Mitja Marató de Barcelona?", "a": "Se celebra habitualmente el segundo domingo de febrero. La fecha exacta se confirma en la web oficial de la prueba normalmente a mediados del año anterior."},
    {"q": "¿Es un circuito rápido para buscar marca?", "a": "Sí, el perfil prácticamente llano con menos de 40 metros de desnivel acumulado y las temperaturas frescas de febrero lo convierten en un circuito ideal para conseguir buenos tiempos y récords personales."},
    {"q": "¿Hay carrera de 10K simultánea?", "a": "Sí, junto a la media maratón se celebra una prueba de 10 kilómetros que comparte parte del recorrido. Es una opción excelente para quienes aún no se sienten preparados para los 21 kilómetros."},
    {"q": "¿Dónde puedo alojarme cerca de la salida y la meta?", "a": "La zona de salida y meta está en la Avenida María Cristina, junto a la Plaza de España. Los hoteles del Eixample y Sants están a distancia caminable y hay excelente conexión en metro con toda la ciudad."},
    {"q": "¿Se puede cambiar el dorsal de nombre si no puedo correr?", "a": "Sí, la organización permite el cambio de titularidad del dorsal hasta una fecha límite que suele ser unas dos semanas antes de la carrera, con un coste administrativo de entre 5 y 10 euros."}
  ],
  "faqEn": [],
  "relatedPlans": ["media-maraton-principiantes", "media-maraton-sub-1-45", "media-maraton-sub-1-30"],
  "relatedEvents": "barcelona"
},

"media-maraton-sevilla": {
  "slugEs": "media-maraton-sevilla",
  "slugEn": "media-maraton-sevilla",
  "hasEn": false,
  "nameEs": "Medio Maratón de Sevilla",
  "nameEn": "",
  "city": "Sevilla",
  "region": "Andalucía",
  "country": "ES",
  "distance": "21.097K",
  "distanceLabel": "Media Maratón",
  "distanceLabelEn": "Half Marathon",
  "distanceCategory": "media-maraton",
  "dateMonth": 1,
  "dateText2026Es": "25 de enero de 2026",
  "dateText2026En": "",
  "startDate": "2026-01-25",
  "priceRange": "20-35",
  "currency": "EUR",
  "maxParticipants": 10000,
  "elevationEs": "Completamente llano, desnivel acumulado inferior a 15 metros",
  "elevationEn": "",
  "heroImage": "https://images.pexels.com/photos/1571940/pexels-photo-1571940.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/2821823/pexels-photo-2821823.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "Medio Maratón de Sevilla 2026: inscripción, recorrido llano junto al Guadalquivir, consejos y FAQ. Corre el 25 de enero con 10.000 participantes en la capital andaluza.",
  "metaDescriptionEn": "",
  "descriptionEs": "El Medio Maratón de Sevilla es una de las pruebas más atractivas del calendario atlético español, gracias a la combinación de un recorrido completamente llano, un clima invernal extraordinariamente benigno y un escenario urbano de belleza incomparable que recorre los monumentos más emblemáticos de la capital andaluza. Celebrado habitualmente en la última semana de enero, este evento reúne a 10.000 corredores que disfrutan de una experiencia deportiva difícil de igualar en cualquier otra ciudad europea en pleno invierno.\n\nSevilla ofrece en enero unas condiciones climáticas privilegiadas para la práctica del running: temperaturas entre los 8 y los 16 grados, cielos generalmente despejados y una humedad moderada que favorece el rendimiento deportivo. Mientras la mayor parte de Europa afronta el duro invierno con temperaturas bajo cero y lluvia, los corredores en Sevilla corren en manga corta junto al Guadalquivir disfrutando de una luminosidad que recuerda más a la primavera que al invierno. Esta ventaja climática ha convertido al Medio Maratón de Sevilla en una opción cada vez más popular entre corredores del norte de Europa que viajan al sur buscando condiciones favorables para sus primeras carreras del año.\n\nEl circuito es absolutamente llano, con un desnivel acumulado que no alcanza los 15 metros en toda la prueba, lo que lo sitúa entre los más planos de España junto con Valencia. El recorrido discurre en gran parte por las márgenes del río Guadalquivir y por las amplias avenidas del centro histórico, pasando junto a la Giralda, la Torre del Oro, la Plaza de España y el Parque de María Luisa, ofreciendo un desfile de postales turísticas que hacen que los kilómetros pasen volando.\n\nLa organización del evento ha mejorado significativamente en las últimas ediciones, acercándose a los estándares de las grandes pruebas nacionales. Los avituallamientos cada 5 kilómetros ofrecen agua, bebida isotónica y frutas, y los puntos de animación con música en directo se distribuyen estratégicamente por el recorrido. La feria del corredor, aunque más modesta que las de Madrid o Valencia, ofrece una selección de marcas deportivas y productos para runners, y la recogida de dorsales es rápida y eficiente.\n\nEl precio de inscripción es notablemente más bajo que el de otras pruebas de similar categoría, situándose entre los 20 y los 35 euros dependiendo del momento de inscripción, lo que lo convierte en una opción muy accesible. Este factor económico, unido a los precios hoteleros y gastronómicos más moderados de Sevilla respecto a Madrid o Barcelona, hace de esta media maratón una excelente relación calidad-precio para un fin de semana deportivo y turístico.\n\nLa medalla finisher de cada edición rinde homenaje a un monumento sevillano diferente, convirtiéndose en un pequeño objeto de coleccionismo para los corredores que repiten año tras año. La meta, ubicada habitualmente en el Paseo de las Delicias junto al río, ofrece una zona de recuperación amplia con servicios de fisioterapia, estiramientos guiados y un completo avituallamiento post-carrera.",
  "descriptionEn": "",
  "routeEs": "El recorrido del Medio Maratón de Sevilla es un circuito urbano completamente llano que discurre en buena parte junto al río Guadalquivir. La salida se da en el Paseo de las Delicias, cerca de la Plaza de España, y los primeros kilómetros transcurren por la avenida que bordea el Parque de María Luisa en dirección al barrio de Los Remedios, cruzando el río por el Puente de San Telmo. El trazado recorre la orilla de Triana antes de regresar al centro histórico por el Puente de Isabel II, pasando junto a la Torre del Oro y la Catedral. Los kilómetros centrales atraviesan las amplias avenidas del casco antiguo, incluyendo la Avenida de la Constitución y la calle San Fernando. El tramo final retorna al Paseo de las Delicias junto al río, con la meta situada en las proximidades de la Fábrica de Tabacos. Los avituallamientos se colocan cada 5 kilómetros con agua y bebida isotónica, y hay puntos de esponjas en los kilómetros 10 y 17.",
  "routeEn": "",
  "tipsEs": [
    "No te confíes con el sol de enero en Sevilla: aunque las mañanas son frescas, el sol puede apretar a media mañana, así que usa protección solar ligera",
    "Llega con tiempo a la salida para disfrutar del ambiente en el Paseo de las Delicias y calentar junto al río sin prisas",
    "Aprovecha el perfil completamente llano para practicar la estrategia de ritmo negativo: empieza conservador y acelera en la segunda mitad",
    "Reserva mesa en el barrio de Triana para la comida posterior: sus bares de tapas son el mejor premio post-carrera",
    "Si vienes de fuera, combina la carrera con una visita al Real Alcázar y la Catedral: el dorsal suele incluir descuentos en atracciones turísticas"
  ],
  "tipsEn": [],
  "faqEs": [
    {"q": "¿Qué tiempo hace en Sevilla en enero para correr?", "a": "Las temperaturas en enero en Sevilla oscilan entre 8 y 16 grados, con cielos generalmente despejados. Son condiciones excelentes para correr, mucho más favorables que en la mayoría de ciudades europeas en esta época del año."},
    {"q": "¿Es un buen circuito para debutar en media maratón?", "a": "Sí, es uno de los mejores circuitos de España para debutar. El perfil completamente llano, el clima suave, el tamaño manejable de 10.000 participantes y el precio económico lo convierten en una opción ideal para correr tu primera media maratón."},
    {"q": "¿Cómo llego al punto de salida?", "a": "El Paseo de las Delicias está bien conectado en autobús urbano de Tussam y en tranvía. También se puede llegar caminando desde el centro en 15 minutos. Se recomienda evitar el coche por los cortes de tráfico."},
    {"q": "¿Hay consigna para dejar mis cosas?", "a": "Sí, la organización habilita un servicio de guardaequipaje gratuito en la zona de salida y meta. Se asigna una bolsa numerada con el dorsal del corredor para facilitar la recogida posterior."},
    {"q": "¿Cuál es el precio de la inscripción?", "a": "El precio oscila entre 20 y 35 euros dependiendo del tramo de inscripción. Los precios más bajos corresponden a los primeros tramos que se abren normalmente en septiembre del año anterior. La inscripción incluye dorsal, camiseta, medalla y bolsa del corredor."}
  ],
  "faqEn": [],
  "relatedPlans": ["media-maraton-principiantes", "media-maraton-sub-1-45", "media-maraton-sub-1-30"],
  "relatedEvents": "sevilla"
},

"media-maraton-malaga": {
  "slugEs": "media-maraton-malaga",
  "slugEn": "media-maraton-malaga",
  "hasEn": false,
  "nameEs": "Medio Maratón de Málaga",
  "nameEn": "",
  "city": "Málaga",
  "region": "Andalucía",
  "country": "ES",
  "distance": "21.097K",
  "distanceLabel": "Media Maratón",
  "distanceLabelEn": "Half Marathon",
  "distanceCategory": "media-maraton",
  "dateMonth": 3,
  "dateText2026Es": "8 de marzo de 2026",
  "dateText2026En": "",
  "startDate": "2026-03-08",
  "priceRange": "20-35",
  "currency": "EUR",
  "maxParticipants": 8000,
  "elevationEs": "Mayormente llano con ligeras ondulaciones, desnivel acumulado de unos 50 metros",
  "elevationEn": "",
  "heroImage": "https://images.pexels.com/photos/3621183/pexels-photo-3621183.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop&q=70",
  "secondImage": "https://images.pexels.com/photos/3621195/pexels-photo-3621195.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&fit=crop&q=70",
  "metaDescriptionEs": "Medio Maratón de Málaga 2026: inscripción, recorrido costero, consejos y preguntas frecuentes. Corre el 8 de marzo con 8.000 participantes junto al Mediterráneo en la Costa del Sol.",
  "metaDescriptionEn": "",
  "descriptionEs": "El Medio Maratón de Málaga es una de las pruebas más atractivas del sur de España y un evento que ha experimentado un crecimiento espectacular en los últimos años, consolidándose como una de las carreras imprescindibles para los runners que buscan combinar deporte, turismo y buen clima en la Costa del Sol. Celebrado habitualmente en el primer o segundo fin de semana de marzo, la prueba reúne a 8.000 corredores en las calles de una ciudad que ha vivido una transformación urbanística y cultural extraordinaria en la última década.\n\nMálaga ofrece en marzo unas condiciones climáticas envidiables para correr: temperaturas entre 10 y 18 grados, abundante sol y la brisa suave del Mediterráneo que refresca sin molestar. Estas condiciones, sumadas a un recorrido que combina tramos costeros con el casco histórico de la ciudad, hacen del Medio Maratón de Málaga una experiencia sensorial completa que va mucho más allá de lo puramente deportivo. Los corredores disfrutan de vistas al mar, del aroma de los jardines de la Alameda y de la arquitectura señorial del centro histórico malagueño.\n\nEl circuito presenta un perfil mayormente llano con ligeras ondulaciones que suman un desnivel acumulado de unos 50 metros, lo que lo convierte en un recorrido asequible para todos los niveles. Las únicas cuestas reseñables se encuentran en el paso por la zona del Puerto y en algún tramo del Paseo del Parque, pero son tan suaves que apenas alteran el ritmo de carrera. El asfalto está generalmente en buen estado y las calles del centro son lo suficientemente anchas para garantizar una circulación fluida del pelotón.\n\nLa organización del medio maratón ha madurado notablemente en las últimas ediciones, ofreciendo un servicio cada vez más profesional. La feria del corredor se celebra en el Palacio de Ferias y Congresos de Málaga (FYCMA) y, aunque más compacta que las de las grandes capitales, ofrece una selección interesante de marcas deportivas y servicios para runners. Los avituallamientos durante la carrera incluyen agua, bebida isotónica y fruta cada 5 kilómetros, y los puntos de animación con música flamenca y batucadas aportan un toque andaluz muy especial.\n\nUno de los grandes atractivos de esta prueba es su precio de inscripción, que se sitúa entre los 20 y los 35 euros según el tramo, lo que la convierte en una de las medias maratones más económicas del circuito nacional. Además, el coste de alojamiento y restauración en Málaga en marzo es significativamente inferior al de los meses de verano, lo que permite organizar un fin de semana deportivo y turístico a un precio muy razonable. Los vuelos low-cost que conectan Málaga con prácticamente toda Europa facilitan la llegada de corredores internacionales.\n\nLa meta se ubica en el Paseo del Parque, uno de los bulevares más hermosos de la ciudad, flanqueado por jardines subtropicales con especies vegetales de los cinco continentes. Los finishers reciben una medalla de diseño exclusivo, camiseta técnica, bolsa del corredor y acceso a la zona de recuperación con fruta, bebida isotónica y servicios de fisioterapia. La cercanía de la meta al centro histórico y al puerto permite una transición perfecta de la carrera a la celebración en los numerosos bares y restaurantes de la zona.",
  "descriptionEn": "",
  "routeEs": "El recorrido del Medio Maratón de Málaga combina tramos costeros con el centro histórico de la ciudad. La salida se da en el Paseo del Parque, junto a la Alameda Principal, y los primeros kilómetros discurren por el paseo marítimo Antonio Banderas en dirección este hacia la playa de la Malagueta y el barrio de Pedregalejo. Tras recorrer varios kilómetros junto al Mediterráneo, el circuito gira hacia el interior por la zona del Puerto y el Muelle Uno, ofreciendo vistas panorámicas del mar y de la Alcazaba. Los kilómetros centrales atraviesan el casco histórico pasando cerca de la Catedral, la calle Larios y la Plaza de la Merced, cuna de Picasso. El trazado regresa al frente marítimo por la zona oeste de la ciudad, recorriendo el Paseo de la Farola y el barrio de Huelin antes de enfilar la recta final por el Paseo del Parque. La meta se sitúa frente a los jardines del ayuntamiento. Los avituallamientos están cada 5 kilómetros con agua, isotónico y fruta.",
  "routeEn": "",
  "tipsEs": [
    "Aplica protección solar incluso en marzo: el sol de Málaga es intenso y la brisa marina puede dar una falsa sensación de frescor",
    "Lleva gafas de sol si eres sensible a la luz porque los tramos junto al mar pueden tener mucho reflejo por la mañana",
    "Aprovecha para explorar la calle Larios y el centro histórico el día antes de la carrera: la recogida de dorsales es rápida y te sobrará tiempo",
    "Si vienes de fuera, reserva hotel en el centro o junto al Paseo del Parque para ir andando a la salida sin necesidad de transporte",
    "Disfruta de un desayuno malagueño ligero dos horas antes de la carrera: una tostada con aceite y un café con leche es la opción local perfecta"
  ],
  "tipsEn": [],
  "faqEs": [
    {"q": "¿Cuándo se celebra el Medio Maratón de Málaga?", "a": "Se celebra habitualmente el primer o segundo domingo de marzo. La fecha exacta se confirma en la web oficial normalmente en el último trimestre del año anterior."},
    {"q": "¿Es apto para debutantes en media maratón?", "a": "Sí, el perfil mayormente llano, el tamaño contenido de 8.000 participantes y el clima agradable de marzo lo convierten en una excelente opción para correr tu primera media maratón sin la presión de las grandes pruebas masivas."},
    {"q": "¿Cómo llego desde el aeropuerto de Málaga al centro?", "a": "El aeropuerto de Málaga-Costa del Sol está a solo 8 kilómetros del centro. La línea C1 de Cercanías conecta el aeropuerto con el centro en 12 minutos por menos de 2 euros. También hay autobús exprés y taxis."},
    {"q": "¿Hay carrera complementaria más corta?", "a": "Sí, junto al medio maratón se celebra habitualmente una prueba de 10 kilómetros que comparte la zona de salida y meta. Es una alternativa perfecta para quienes aún no están preparados para los 21 kilómetros."},
    {"q": "¿Qué incluye la inscripción?", "a": "La inscripción incluye dorsal con chip de cronometraje, camiseta técnica oficial, medalla finisher, bolsa del corredor con productos de patrocinadores, seguro médico y acceso a la zona de recuperación post-meta."}
  ],
  "faqEn": [],
  "relatedPlans": ["media-maraton-principiantes", "media-maraton-sub-1-45", "media-maraton-sub-1-30"],
  "relatedEvents": "malaga"
}

};

console.log(JSON.stringify(data, null, 2));
